// cleanui-admin-template-vue/src/views/ecommerce/products-list/index.vue
<template>
  <div class="card">
    <div class="card-header">
      <div class="utils__title">
        <strong>Product List</strong>
      </div>
    </div>
    <div class="card-body">
      <a-table
        :columns="columns"
        :dataSource="data"
        class="utils__scrollTable"
        :scroll="{ x: '100%' }"
      >
        <a
          slot="id"
          slot-scope="value"
          class="utils__link--underlined"
          href="javascript: void(0);"
        >#{{value}}</a>
        <a
          slot="thumbnail"
          slot-scope="value"
          :class="$style.thumbnail"
          href="javascript: void(0);"
        >
          <img :src="value">
        </a>
        <div
          slot="filterDropdown"
          slot-scope="{ setSelectedKeys, selectedKeys, confirm, clearFilters, column }"
          class="custom-filter-dropdown"
        >
          <a-input
            v-ant-ref="c => searchInput = c"
            :placeholder="`Search ${column.dataIndex}`"
            :value="selectedKeys[0]"
            @change="e => setSelectedKeys(e.target.value ? [e.target.value] : [])"
            @pressEnter="() => handleSearch(selectedKeys, confirm)"
            style="width: 188px; margin-bottom: 8px; display: block;"
          />
          <a-button
            type="primary"
            @click="() => handleSearch(selectedKeys, confirm)"
            icon="search"
            size="small"
            style="width: 90px; margin-right: 8px"
          >Search</a-button>
          <a-button @click="() => handleReset(clearFilters)" size="small" style="width: 90px">Reset</a-button>
        </div>
        <a-icon
          slot="filterIcon"
          slot-scope="filtered"
          type="search"
          :style="{ color: filtered ? '#108ee9' : undefined }"
        />
        <template slot="customRender" slot-scope="text">
          <span v-if="searchText">
            <template
              v-for="(fragment, i) in text.toString().split(new RegExp(`(?<=${searchText})|(?=${searchText})`, 'i'))"
            >
              <mark
                v-if="fragment.toLowerCase() === searchText.toLowerCase()"
                :key="i"
                class="highlight"
              >{{fragment}}</mark>
              <template v-else>{{fragment}}</template>
            </template>
          </span>
          <template v-else>{{text}}</template>
        </template>
        <span slot="price" slot-scope="value">${{value}}</span>
        <span
          slot="status"
          slot-scope="value"
          class="font-size-12 badge"
          :class="[value === 'Enabled' ? 'badge-success' : 'badge-danger']"
        >{{value}}</span>
        <span slot="action">
          <a-button icon="edit" size="small" class="mr-1">View</a-button>
          <a-button icon="cross" size="small">Remove</a-button>
        </span>
      </a-table>
    </div>
  </div>
</template>

<script>
import { data } from './data.json'

export default {
  data: function () {
    return {
      data,
      searchText: '',
      searchInput: null,
      columns: [
        {
          title: 'ID',
          dataIndex: 'id',
          key: 'id',
          sorter: (a, b) => a.id - b.id,
          scopedSlots: {
            customRender: 'id',
          },
        },
        {
          title: 'Thumbnail',
          dataIndex: 'thumbnail',
          key: 'thumbnail',
          scopedSlots: {
            customRender: 'thumbnail',
          },
        },
        {
          title: 'Name',
          dataIndex: 'name',
          key: 'name',
          sorter: (a, b) => a.name.length - b.name.length,
          scopedSlots: {
            filterDropdown: 'filterDropdown',
            filterIcon: 'filterIcon',
            customRender: 'customRender',
          },
          onFilter: (value, record) => record.name.toLowerCase().includes(value.toLowerCase()),
          onFilterDropdownVisibleChange: (visible) => {
            if (visible) {
              setTimeout(() => {
                this.searchInput.focus()
              }, 0)
            }
          },
        },
        {
          title: 'Type',
          dataIndex: 'type',
          key: 'type',
          sorter: (a, b) => a.type.length - b.type.length,
        },
        {
          title: 'Attribute Set',
          dataIndex: 'attribute',
          key: 'attribute',
          sorter: (a, b) => a.attribute.length - b.attribute.length,
        },
        {
          title: 'SKU',
          dataIndex: 'sku',
          key: 'sku',
          sorter: (a, b) => a.sku.length - b.sku.length,
        },
        {
          title: 'Price',
          dataIndex: 'price',
          key: 'price',
          scopedSlots: {
            customRender: 'price',
          },
        },
        {
          title: 'Quantity',
          dataIndex: 'quantity',
          key: 'quantity',
          sorter: (a, b) => a.quantity - b.quantity,
        },
        {
          title: 'Status',
          dataIndex: 'status',
          key: 'status',
          sorter: (a, b) => a.status.length - b.status.length,
          scopedSlots: {
            customRender: 'status',
          },
        },
        {
          title: 'Action',
          key: 'action',
          scopedSlots: {
            customRender: 'action',
          },
        },
      ],
    }
  },
  methods: {
    handleSearch(selectedKeys, confirm) {
      confirm()
      this.searchText = selectedKeys[0]
    },

    handleReset(clearFilters) {
      clearFilters()
      this.searchText = ''
    },
  },
}
</script>

<style lang="scss" module scoped>
@import "./style.module.scss";
</style>

// cleanui-admin-template-angular/src/app/pages/ecommerce/products-list/products-list.component.ts
import { Component } from '@angular/core'
declare var require: any
const data: any = require('./data.json')

@Component({
  selector: 'app-ecommerce-products-list',
  templateUrl: './products-list.component.html',
  styleUrls: ['./products-list.component.scss'],
})
export class EcommerceProductsListComponent {
  productsData = data.data
  displayProductsData = [...this.productsData]
  sortName = null
  sortValue = null
  listOfSearchName = []
  searchAddress: string

  sort(sort: { key: string; value: string }): void {
    this.sortName = sort.key
    this.sortValue = sort.value
    this.search()
  }

  filter(listOfSearchName: string[], searchAddress: string): void {
    this.listOfSearchName = listOfSearchName
    this.searchAddress = searchAddress
    this.search()
  }

  search(): void {
    // /** filter data **/
    const filterFunc = item =>
      (this.searchAddress ? item.address.indexOf(this.searchAddress) !== -1 : true) &&
      (this.listOfSearchName.length
        ? this.listOfSearchName.some(name => item.name.indexOf(name) !== -1)
        : true)
    const data = this.productsData.filter(item => filterFunc(item))
    /** sort data **/
    if (this.sortName && this.sortValue) {
      this.displayProductsData = data.sort((a, b) =>
        this.sortValue === 'ascend'
          ? a[this.sortName] > b[this.sortName]
            ? 1
            : -1
          : b[this.sortName] > a[this.sortName]
          ? 1
          : -1,
      )
    } else {
      this.displayProductsData = data
    }
  }
}

<div class="card">
  <div class="card-header">
    <div class="utils__title">
      <strong>
        Products List
      </strong>
    </div>
  </div>
  <div class="card-body">
    <nz-table #productsTable [nzData]="displayProductsData">
      <thead (nzSortChange)="sort($event)" nzSingleSort>
      <tr>
        <th nzShowSort nzSortKey="id">ID</th>
        <th>Thumbnail</th>
        <th nzShowSort nzSortKey="name">Name</th>
        <th nzShowSort nzSortKey="type">Type</th>
        <th nzShowSort nzSortKey="attribute">Attribute Set</th>
        <th nzShowSort nzSortKey="sku">SKU</th>
        <th nzShowSort nzSortKey="price">Price</th>
        <th nzShowSort nzSortKey="quantity">Quantity</th>
        <th nzShowSort nzSortKey="status">Status</th>
        <th>Action</th>
      </tr>
      </thead>
      <tbody>
      <tr *ngFor="let item of productsTable.data">
        <td>
          <a href="javascript: void(0);" class="utils__link--underlined">
            #{{item.id}}
          </a>
        </td>
        <td>
          <a href="javascript: void(0);" class="cui-product-list-thumbnail">
            <img [src]="item.thumbnail" />
          </a>
        </td>
        <td>
          <a class="utils__link--underlined" href="javascript: void(0);">
            {{item.name}}
          </a>
        </td>
        <td>
          {{item.attribute}}
        </td>
        <td>
          {{item.type}}
        </td>
        <td>
          {{item.sku}}
        </td>
        <td>
          ${{item.price}}
        </td>
        <td>
          {{item.quantity}}
        </td>
        <td>
          <span [ngClass]="[item.status === 'Disabled' ? 'badge badge-danger font-size-12' : 'badge badge-success font-size-12']">
            {{item.status}}
          </span>
        </td>
        <td>
          <button nz-button class="mr-1" nzSize="small"><i nz-icon type="edit" theme="outline"></i> View</button>
          <button nz-button class="mr-1" nzSize="small"><i nz-icon type="delete" theme="outline"></i> Remove</button>
        </td>
      </tr>
      </tbody>
    </nz-table>
  </div>
</div>
