// cleanui-admin-template-vue/src/views/apps/profile/index.vue
<template>
  <div :class="$style.profile">
    <div class="row">
      <div class="col-xl-4">
        <div
          class="card"
          :class="$style.header"
          :style="{ backgroundImage: 'url(' + background + ')'}"
        >
          <div class="card-body text-center">
            <cui-avatar :src="photo" size="110" bordered="true" :borderColor="white"/>
            <br>
            <br>
            <a-button-group>
              <a-button style="width: 150px;">Follow</a-button>
              <a-button style="width: 150px;">Add to Friend</a-button>
            </a-button-group>
            <br>
            <p class="text-white mt-2">Last activity: {{lastActivity}}</p>
            <p class="text-white mt-2">
              <cui-donut :name="status" :type="status === 'Online' ? 'success' : 'danger'"/>
            </p>
          </div>
        </div>
        <div class="card">
          <div class="card-body">
            <h5 class="mb-3 text-black">
              <strong>Actions</strong>
            </h5>
            <div :class="$style.actions">
              <a-button style="display: block; width: 100%;">Send Message</a-button>
              <a-button style="display: block; width: 100%;">Send File</a-button>
              <a-button style="display: block; width: 100%;">Access History</a-button>
              <a-button style="display: block; width: 100%;">Rename User</a-button>
              <a-button style="display: block; width: 100%;">Ban User</a-button>
            </div>
          </div>
        </div>
        <div class="card">
          <div class="card-body">
            <h5 class="mb-3 text-black">
              <strong>Skills</strong>
            </h5>
            <div v-for="(skill, index) in skills" :key="index">
              <div class="mb-1">{{skill.name}}</div>
              <a-progress :percent="skill.value" :showInfo="false"/>
            </div>
          </div>
        </div>
        <div class="card">
          <div class="card-body">
            <h5 class="mb-3 text-black">
              <strong>Information</strong>
            </h5>
            <dl class="row">
              <dt class="col-xl-3">Courses End:</dt>
              <dd class="col-xl-9">{{coursesEnd}}</dd>
              <dt class="col-xl-3">Address:</dt>
              <dd class="col-xl-9">{{adress}}</dd>
              <dt class="col-xl-3">Skills:</dt>
              <dd class="col-xl-9">
                <span
                  class="badge badge-default mr-1"
                  :key="index"
                  v-for="(skill, index) in profSkills"
                >{{skill}}</span>
              </dd>
              <dt class="col-xl-3">Last companies:</dt>
              <dd class="col-xl-9">{{lastCompanies}}</dd>
              <dt class="col-xl-3">Personal Information:</dt>
              <dd class="col-xl-9">{{personal}}</dd>
            </dl>
          </div>
        </div>
        <div class="card">
          <div class="card-body">
            <h5 class="mb-3 text-black">
              <strong>Calendar</strong>
            </h5>
            <a-calendar :fullscreen="false"/>
          </div>
        </div>
      </div>
      <div class="col-xl-8">
        <div :class="$style.socialInfo" class="card card-body mb-4">
          <div>
            <h2>
              <span class="text-black mr-2">
                <strong>{{name}}</strong>
              </span>
              <small class="text-muted">{{nickname}}</small>
            </h2>
            <p class="mb-1">{{post}}</p>
          </div>
          <div :class="$style.socialCounts">
            <div class="text-center mr-3">
              <h2>{{followersCount}}</h2>
              <p class="mb-0">Followers</p>
            </div>
            <div class="text-center mr-3">
              <h2>{{postsCount}}</h2>
              <p class="mb-0">Followers</p>
            </div>
          </div>
        </div>
        <div class="card">
          <div class="card-body">
            <a-tabs defaultActiveKey="1">
              <a-tab-pane key="1">
                <span slot="tab">
                  <span>
                    <i class="icmn-menu"/> Wall
                  </span>
                </span>
                <div class="py-3">
                  <a-textarea placeholder="Basic usage" :rows="4"/>
                  <div class="mt-3">
                    <a-button class="mr-2" type="primary" style="width: 200px">
                      <i class="fa fa-send mr-2"/>
                      Create Post
                    </a-button>
                    <a-upload
                      name="file"
                      :multiple="true"
                      action="//jsonplaceholder.typicode.com/posts/"
                      :headers="headers"
                      @change="handleChange"
                    >
                      <a-button>
                        <a-icon type="upload"/>Click to Upload
                      </a-button>
                    </a-upload>
                  </div>
                </div>
                <div v-for="(item, index) in posts" :key="index">
                  <div :class="$style.wallItem" class="clearfix">
                    <div :class="$style.wallAvatar">
                      <cui-avatar size="50" :src="item.avatar" :bordered="false"/>
                    </div>
                    <div :class="$style.wallContent">
                      <div class="mb-3">
                        <div class="pull-right">
                          <a-dropdown>
                            <a class="ant-dropdown-link" href="javascript: void(0);">Actions
                              <a-icon type="down"/>
                            </a>
                            <a-menu slot="overlay">
                              <a-menu-item>
                                <a href="javascript:void(0)">
                                  <a-icon type="edit"/>Edit Post
                                </a>
                              </a-menu-item>
                              <a-menu-item>
                                <a href="javascript:void(0)">
                                  <a-icon type="delete"/>Delete Post
                                </a>
                              </a-menu-item>
                              <a-menu-item>
                                <a href="javascript:void(0)">
                                  <a-icon type="frown-o"/>Mark as a Spam
                                </a>
                              </a-menu-item>
                            </a-menu>
                          </a-dropdown>
                        </div>
                        <strong>{{item.name}}</strong> posted:
                        <br>
                        <small class="text-muted">{{item.date}}</small>
                      </div>
                      <div class="mb-3" v-html="item.content"></div>
                      <a href="javascript: void(0);" class="mr-3">
                        <i class="icmn-heart mr-2"/>
                        <span v-if="item.likesCount > 0">{{item.likesCount}} Likes</span>
                        <span v-if="item.likesCount === 0">{{item.likesCount}} Like</span>
                      </a>
                      <a href="javascript: void(0);" class="mr-3">
                        <i class="icmn-bubble mr-2"/>
                        <span v-if="item.commentsCount > 0">{{item.commentsCount}} Comments</span>
                        <span v-if="item.commentsCount === 0">{{item.commentsCount}} Comment</span>
                      </a>
                    </div>
                  </div>
                  <div :class="[$style.wallContent, $style.wallInnerContent]">
                    <div :class="$style.wallComments">
                      <div
                        :class="$style.wallItem"
                        class="clearfix"
                        v-for="(postComment, index) in item.comments"
                        :key="index"
                      >
                        <div :class="$style.wallAvatar">
                          <cui-avatar size="50" :src="postComment.avatar" :bordered="false"/>
                        </div>
                        <div :class="$style.wallContent">
                          <div class="clearfix">
                            <div class="pull-right">
                              <a-dropdown>
                                <a class="ant-dropdown-link" href="javascript: void(0);">Actions
                                  <a-icon type="down"/>
                                </a>
                                <a-menu slot="overlay">
                                  <a-menu-item>
                                    <a href="javascript:void(0)">
                                      <a-icon type="edit"/>Edit Post
                                    </a>
                                  </a-menu-item>
                                  <a-menu-item>
                                    <a href="javascript:void(0)">
                                      <a-icon type="delete"/>Delete Post
                                    </a>
                                  </a-menu-item>
                                  <a-menu-item>
                                    <a href="javascript:void(0)">
                                      <a-icon type="frown-o"/>Mark as a Spam
                                    </a>
                                  </a-menu-item>
                                </a-menu>
                              </a-dropdown>
                            </div>
                            <strong>{{postComment.name}}</strong> posted:
                            <br>
                            <small class="text-muted">{{postComment.date}}</small>
                          </div>
                          <div class="mb-3" v-html="postComment.content"></div>
                          <a href="javascript: void(0);" class="mr-3">
                            <i class="icmn-heart mr-2"/>
                            <span v-if="postComment.likesCount > 0">{{postComment.likesCount}} Likes</span>
                            <span
                              v-if="postComment.likesCount === 0"
                            >{{postComment.likesCount}} Like</span>
                          </a>
                          <a href="javascript: void(0);" class="mr-3">
                            <i class="icmn-bubble mr-2"/>
                            <span
                              v-if="postComment.commentsCount > 0"
                            >{{postComment.commentsCount}} Comments</span>
                            <span
                              v-if="postComment.commentsCount === 0"
                            >{{postComment.commentsCount}} Comment</span>
                          </a>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </a-tab-pane>
              <a-tab-pane key="2">
                <span slot="tab">
                  <span>
                    <i class="icmn-bubbles"/> Messages
                  </span>
                </span>
                <cui-chat/>
              </a-tab-pane>
              <a-tab-pane key="3">
                <span slot="tab">
                  <i class="icmn-cog"/> Settings
                </span>
                <a-form :form="form">
                  <h5 class="text-black mt-2 mb-3">
                    <strong>Personal Information</strong>
                  </h5>
                  <div class="row">
                    <div class="col-lg-6">
                      <a-form-item label="Username">
                        <a-input placeholder="Username" v-decorator="['username']"/>
                      </a-form-item>
                    </div>
                    <div class="col-lg-6">
                      <a-form-item label="Email">
                        <a-input placeholder="Email" v-decorator="['discount']"/>
                      </a-form-item>
                    </div>
                  </div>
                  <h5 class="text-black mt-2 mb-3">
                    <strong>New Password</strong>
                  </h5>
                  <div class="row">
                    <div class="col-lg-6">
                      <a-form-item label="Password">
                        <a-input placeholder="Password" v-decorator="['password']"/>
                      </a-form-item>
                    </div>
                    <div class="col-lg-6">
                      <a-form-item label="Confirm Password">
                        <a-input placeholder="Confirm Password" v-decorator="['confirmPassword']"/>
                      </a-form-item>
                    </div>
                  </div>
                  <div class="row">
                    <div class="col-lg-6">
                      <h5 class="text-black mt-2 mb-3">
                        <strong>Profile Avatar</strong>
                      </h5>
                      <a-form-item>
                        <a-upload
                          name="file"
                          :multiple="true"
                          action="//jsonplaceholder.typicode.com/posts/"
                          :headers="headers"
                          @change="handleChange"
                        >
                          <a-button>
                            <a-icon type="upload"/>Click to Upload
                          </a-button>
                        </a-upload>
                      </a-form-item>
                    </div>
                    <div class="col-lg-6">
                      <h5 class="text-black mt-2 mb-3">
                        <strong>Profile Background</strong>
                      </h5>
                      <a-form-item>
                        <a-upload
                          name="file"
                          :multiple="true"
                          action="//jsonplaceholder.typicode.com/posts/"
                          :headers="headers"
                          @change="handleChange"
                        >
                          <a-button>
                            <a-icon type="upload"/>Click to Upload
                          </a-button>
                        </a-upload>
                      </a-form-item>
                    </div>
                  </div>
                  <div class="form-actions mt-0">
                    <a-button
                      style="width: 150px;"
                      type="primary"
                      htmlType="submit"
                      class="mr-3"
                    >Submit</a-button>
                    <a-button htmlType="submit">Cancel</a-button>
                  </div>
                </a-form>
              </a-tab-pane>
            </a-tabs>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import {
  name,
  nickname,
  photo,
  background,
  post,
  postsCount,
  followersCount,
  lastActivity,
  status,
  skills,
  coursesEnd,
  adress,
  profSkills,
  lastCompanies,
  personal,
  posts,
} from './data.json'
import CuiAvatar from '@/components/CleanUIComponents/Avatar'
import CuiDonut from '@/components/CleanUIComponents/Donut'
import CuiChat from '@/components/CleanUIComponents/Chat'

export default {
  components: {
    CuiAvatar,
    CuiDonut,
    CuiChat,
  },
  data: function () {
    return {
      name,
      nickname,
      photo,
      background,
      post,
      postsCount,
      followersCount,
      lastActivity,
      status,
      skills,
      coursesEnd,
      adress,
      profSkills,
      lastCompanies,
      personal,
      posts,
      form: this.$form.createForm(this),
    }
  },
  methods: {
    handleChange(info) {
      if (info.file.status !== 'uploading') {
        console.log(info.file, info.fileList)
      }
      if (info.file.status === 'done') {
        this.$message.success(`${info.file.name} file uploaded successfully`)
      } else if (info.file.status === 'error') {
        this.$message.error(`${info.file.name} file upload failed.`)
      }
    },
  },
}
</script>

<style lang="scss" module>
@import "./style.module.scss";
</style>

// cleanui-admin-template-react-umi/src/pages/apps/profile/index.js
import React from 'react'
import { Button, Progress, Calendar, Tabs, Upload, Icon, Input, Menu, Dropdown } from 'antd'
import { Helmet } from 'react-helmet'
import data from './data.json'
import style from './style.module.scss'
import Avatar from '@/components/CleanUIComponents/Avatar'
import Donut from '@/components/CleanUIComponents/Donut'
import Chat from '@/components/CleanUIComponents/Chat'
import SettingsForm from './SettingsForm'

const { TabPane } = Tabs
const { TextArea } = Input

const actions = (
  <Menu>
    <Menu.Item>
      <Icon type="edit" /> Edit Post
    </Menu.Item>
    <Menu.Item>
      <Icon type="delete" /> Delete Post
    </Menu.Item>
    <Menu.Item>
      <Icon type="frown-o" /> Mark as a Spam
    </Menu.Item>
  </Menu>
)

class ProfileApp extends React.Component {
  state = {
    name: '',
    nickname: '',
    photo: '',
    background: '',
    post: '',
    postsCount: '',
    followersCount: '',
    lastActivity: '',
    status: '',
  }

  componentWillMount() {
    this.setState({
      name: data.name,
      nickname: data.nickname,
      photo: data.photo,
      background: data.background,
      post: data.post,
      postsCount: data.postsCount,
      followersCount: data.followersCount,
      lastActivity: data.lastActivity,
      status: data.status,
      skills: data.skills,
      coursesEnd: data.coursesEnd,
      adress: data.adress,
      profSkills: data.profSkills,
      lastCompanies: data.lastCompanies,
      personal: data.personal,
      posts: data.posts,
    })
  }

  render() {
    const {
      name,
      nickname,
      photo,
      background,
      post,
      postsCount,
      followersCount,
      lastActivity,
      status,
      skills,
      coursesEnd,
      adress,
      profSkills,
      lastCompanies,
      personal,
      posts,
    } = this.state

    return (
      <div>
        <Helmet title="Profile" />
        <div className={style.profile}>
          <div className="row">
            <div className="col-xl-4">
              <div
                className={`card ${style.header}`}
                style={{ backgroundImage: `url(${background})` }}
              >
                <div>
                  <div className="card-body text-center">
                    <Avatar src={photo} size="110" border="true" borderColor="white" />
                    <br />
                    <br />
                    <Button.Group size="default">
                      <Button style={{ width: 150 }}>Follow</Button>
                      <Button style={{ width: 150 }}>Add to Friend</Button>
                    </Button.Group>
                    <br />
                    <p className="text-white mt-2">{`Last activity: ${lastActivity}`}</p>
                    <p className="text-white mt-2">
                      {status === 'Online' && <Donut type="success" name={status} />}
                      {status === 'Offline' && <Donut type="danger" name={status} />}
                    </p>
                  </div>
                </div>
              </div>
              <div className="card">
                <div className="card-body">
                  <h5 className="mb-3 text-black">
                    <strong>Actions</strong>
                  </h5>
                  <div className={style.actions}>
                    <Button style={{ display: 'block', width: '100%' }}>Send Message</Button>
                    <Button style={{ display: 'block', width: '100%' }}>Send File</Button>
                    <Button style={{ display: 'block', width: '100%' }}>Access History</Button>
                    <Button style={{ display: 'block', width: '100%' }}>Rename User</Button>
                    <Button style={{ display: 'block', width: '100%' }}>Ban User</Button>
                  </div>
                </div>
              </div>
              <div className="card">
                <div className="card-body">
                  <h5 className="mb-3 text-black">
                    <strong>Skills</strong>
                  </h5>
                  {skills.map(skill => (
                    <div key={skill.name}>
                      <div className="mb-1">{skill.name}</div>
                      <Progress percent={skill.value} showInfo={false} />
                    </div>
                  ))}
                </div>
              </div>
              <div className="card">
                <div className="card-body">
                  <h5 className="mb-3 text-black">
                    <strong>Information</strong>
                  </h5>
                  <dl className="row">
                    <dt className="col-xl-3">Courses End:</dt>
                    <dd className="col-xl-9">{coursesEnd}</dd>
                    <dt className="col-xl-3">Address:</dt>
                    <dd className="col-xl-9">{adress}</dd>
                    <dt className="col-xl-3">Skills:</dt>
                    <dd className="col-xl-9">
                      {profSkills.map(skill => (
                        <span className="badge badge-default mr-1" key={skill}>
                          {skill}
                        </span>
                      ))}
                    </dd>
                    <dt className="col-xl-3">Last companies:</dt>
                    <dd className="col-xl-9">{lastCompanies}</dd>
                    <dt className="col-xl-3">Personal Information:</dt>
                    <dd className="col-xl-9">{personal}</dd>
                  </dl>
                </div>
              </div>
              <div className="card">
                <div className="card-body">
                  <h5 className="mb-3 text-black">
                    <strong>Calendar</strong>
                  </h5>
                  <Calendar fullscreen={false} />
                </div>
              </div>
            </div>
            <div className="col-xl-8">
              <div className={`card card-body mb-4 ${style.socialInfo}`}>
                <div>
                  <h2>
                    <span className="text-black mr-2">
                      <strong>{name}</strong>
                    </span>
                    <small className="text-muted">{nickname}</small>
                  </h2>
                  <p className="mb-1">{post}</p>
                </div>
                <div className={style.socialCounts}>
                  <div className="text-center mr-3">
                    <h2>{followersCount}</h2>
                    <p className="mb-0">Followers</p>
                  </div>
                  <div className="text-center">
                    <h2>{postsCount}</h2>
                    <p className="mb-0">Posts</p>
                  </div>
                </div>
              </div>
              <div className="card">
                <div className="card-body">
                  <Tabs defaultActiveKey="1">
                    <TabPane
                      tab={
                        <span>
                          <i className="icmn-menu" /> Wall
                        </span>
                      }
                      key="1"
                    >
                      <div className="py-3">
                        <TextArea rows={3} />
                        <div className="mt-3">
                          <Button className="mr-2" type="primary" style={{ width: 200 }}>
                            <i className="fa fa-send mr-2" />
                            Create Post
                          </Button>
                          <Upload>
                            <Button>
                              <Icon type="upload" /> Attach File
                            </Button>
                          </Upload>
                        </div>
                      </div>
                      <hr />
                      {posts.map(item => (
                        <div key={item.name}>
                          <div className={`${style.wallItem} clearfix`}>
                            <div className={style.wallAvatar}>
                              <Avatar size="50" src={item.avatar} border={false} />
                            </div>
                            <div className={style.wallContent}>
                              <div className="mb-3">
                                <div className="pull-right">
                                  <Dropdown overlay={actions}>
                                    <a className="ant-dropdown-link" href="javascript: void(0);">
                                      Actions <Icon type="down" />
                                    </a>
                                  </Dropdown>
                                </div>
                                <strong>{item.name}</strong> posted:
                                <br />
                                <small className="text-muted">{item.date}</small>
                              </div>
                              <div
                                dangerouslySetInnerHTML={{ __html: item.content }}
                                className="mb-3"
                              />
                              <div className="mr-3">
                                <a href="javascript: void(0);" className="mr-3">
                                  <i className="icmn-heart mr-2" />
                                  {item.likesCount > 0 && <span>{`${item.likesCount} Likes`}</span>}
                                  {item.likesCount === 0 && (
                                    <span>{`${item.likesCount} Like`}</span>
                                  )}
                                </a>
                                <a href="javascript: void(0);">
                                  <i className="icmn-bubble mr-2" />
                                  {item.commentsCount > 0 && (
                                    <span>{`${item.commentsCount} Comments`}</span>
                                  )}
                                  {item.commentsCount === 0 && (
                                    <span>{`${item.commentsCount} Comment`}</span>
                                  )}
                                </a>
                              </div>
                            </div>
                          </div>
                          <div className={`${style.wallContent} ${style.wallInnerContent}`}>
                            {item.comments.length > 0 && (
                              <div className={style.wallComments}>
                                {item.comments.map(postComment => (
                                  <div
                                    className={`${style.wallItem} clearfix`}
                                    key={postComment.name}
                                  >
                                    <div className={style.wallAvatar}>
                                      <Avatar size="50" src={postComment.avatar} border={false} />
                                    </div>
                                    <div className={style.wallContent}>
                                      <div className="mb-3">
                                        <div className="pull-right">
                                          <Dropdown overlay={actions}>
                                            <a
                                              className="ant-dropdown-link"
                                              href="javascript: void(0);"
                                            >
                                              Actions <Icon type="down" />
                                            </a>
                                          </Dropdown>
                                        </div>
                                        <strong>{postComment.name}</strong> posted:
                                        <br />
                                        <small className="text-muted">{postComment.date}</small>
                                      </div>
                                      <div
                                        dangerouslySetInnerHTML={{ __html: postComment.content }}
                                      />
                                      <div>
                                        <a href="javascript: void(0);" className="mr-2">
                                          <i className="icmn-heart mr-2" />
                                          {postComment.likesCount > 0 && (
                                            <span>{`${postComment.likesCount} Likes`}</span>
                                          )}
                                          {postComment.likesCount === 0 && (
                                            <span>{`${postComment.likesCount} Like`}</span>
                                          )}
                                        </a>
                                      </div>
                                    </div>
                                  </div>
                                ))}
                              </div>
                            )}
                          </div>
                          <div className="form-group mt-4 mb-0">
                            <TextArea rows={3} />
                            <div className="mt-3">
                              <Button className="mr-2" type="primary" style={{ width: 200 }}>
                                <i className="fa fa-send mr-2" />
                                Comment
                              </Button>
                              <Upload>
                                <Button>
                                  <Icon type="upload" /> Attach File
                                </Button>
                              </Upload>
                            </div>
                          </div>
                        </div>
                      ))}
                    </TabPane>
                    <TabPane
                      tab={
                        <span>
                          <i className="icmn-bubbles" /> Messages
                        </span>
                      }
                      key="2"
                    >
                      <Chat />
                    </TabPane>
                    <TabPane
                      tab={
                        <span>
                          <i className="icmn-cog" /> Settings
                        </span>
                      }
                      key="3"
                    >
                      <SettingsForm />
                    </TabPane>
                  </Tabs>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    )
  }
}

export default ProfileApp
