// cleanui-admin-template-react-umi-seed/src/components/LayoutComponents/TopBar/IssuesHistory/index.js
import React from 'react'
import { Menu, Dropdown } from 'antd'
import { formatMessage } from 'umi/locale'
import Link from 'umi/link'
import styles from './style.module.scss'

class IssuesHistory extends React.Component {
  render() {
    const menu = (
      <Menu selectable={false}>
        <Menu.Item>
          <Link to="/">Current search</Link>
        </Menu.Item>
        <Menu.Item>
          <Link to="/">Search for issues</Link>
        </Menu.Item>
        <Menu.Divider />
        <span className={styles.title}>
          <strong>Opened</strong>
        </span>
        <Menu.Item>
          <Link to="/">
            <i className={`${styles.menuIcon} icmn-checkmark`} />
            CLNUI-253 Project implemen...
          </Link>
        </Menu.Item>
        <Menu.Item>
          <Link to="/">
            <i className={`${styles.menuIcon} icmn-checkmark`} />
            CLNUI-234 Active history iss...
          </Link>
        </Menu.Item>
        <Menu.Item>
          <Link to="/">
            <i className={`${styles.menuIcon} icmn-clock`} />
            CLNUI-424 Ionicons intergrat...
          </Link>
        </Menu.Item>
        <Menu.Item>
          <Link to="/">More...</Link>
        </Menu.Item>
        <Menu.Divider />
        <span className={styles.title}>
          <strong>Filters</strong>
        </span>
        <Menu.Item>
          <Link to="/">My open issues</Link>
        </Menu.Item>
        <Menu.Item>
          <Link to="/">Reported by me</Link>
        </Menu.Item>
        <Menu.Divider />
        <Menu.Item>
          <Link to="/">
            <i className={`${styles.menuIcon} icmn-cog`} /> Settings
          </Link>
        </Menu.Item>
      </Menu>
    )
    return (
      <Dropdown overlay={menu} trigger={['click']} placement="bottomLeft">
        <div className={styles.dropdown}>
          <i className={`${styles.icon} icmn-folder-open`} />
          <span className="d-none d-xl-inline">
            <strong>{formatMessage({ id: 'topBar.issuesHistory' })}</strong>
          </span>
        </div>
      </Dropdown>
    )
  }
}

export default IssuesHistory

// cleanui-admin-template-vue/src/components/LayoutComponents/Topbar/IssuesHistory/index.vue
<template>
  <a-dropdown :trigger="['click']" placement="bottomLeft">
    <div :class="$style.dropdown">
      <i class="icmn-folder-open" :class="$style.icon"></i>
      <span class="d-none d-xl-inline">
        <strong>Issues History</strong>
      </span>
    </div>
    <a-menu slot="overlay">
      <a-menu-item key="1">
        <a href="javascript: void(0);">Current search</a>
      </a-menu-item>
      <a-menu-item>
        <a href="javascript: void(0);">Search for issues</a>
      </a-menu-item>
      <a-menu-divider/>
      <a-menu-item-group title="Opened">
        <a-menu-item>
          <a href="javascript: void(0);">
            <i class="icmn-checkmark" :class="$style.menuIcon"/>
            CLNUI-253 Project implemen...
          </a>
        </a-menu-item>
        <a-menu-item>
          <a href="javascript: void(0);">
            <i class="icmn-checkmark" :class="$style.menuIcon"/>
            CLNUI-234 Active history iss...
          </a>
        </a-menu-item>
        <a-menu-item>
          <a href="javascript: void(0);">
            <i class="icmn-checkmark" :class="$style.menuIcon"/>
            CLNUI-424 Ionicons intergrat...
          </a>
        </a-menu-item>
        <a-menu-item>
          <a href="javascript: void(0);">More...</a>
        </a-menu-item>
      </a-menu-item-group>
      <a-menu-divider/>
      <a-menu-item-group title="Filters">
        <a-menu-item>
          <a href="javascript: void(0);">My open issues</a>
        </a-menu-item>
        <a-menu-item>
          <a href="javascript: void(0);">Reported by me</a>
        </a-menu-item>
      </a-menu-item-group>
      <a-menu-divider/>
      <a-menu-item>
        <a href="javascript: void(0);">
          <i class="icmn-cog" :class="$style.menuIcon"/>
          Settings
        </a>
      </a-menu-item>
    </a-menu>
  </a-dropdown>
</template>

<style lang="scss" module>
@import "./style.module.scss";
</style>
