// cleanui-admin-template-angular/src/app/pages/apps/gallery/gallery.component.ts
import { Component, OnInit } from '@angular/core'
declare var require: any
const data: any = require('./data.json')

@Component({
  selector: 'app-app-gallery',
  templateUrl: './gallery.component.html',
  styleUrls: ['./gallery.component.scss'],
})
export class AppsGalleryComponent implements OnInit {
  galleryData = data.images

  ngOnInit() {}
}

<div class="card">
  <div class="card-header clearfix">
    <div class="utils__title pull-left">
      <strong>Photo Gallery</strong>
    </div>
    <div class="pull-right">
      <nz-upload
        nzAction="https://jsonplaceholder.typicode.com/posts/"
      >
        <button nz-button nzType="primary">
          <i nz-icon type="upload"></i><span>Upload</span>
        </button>
      </nz-upload>
    </div>
  </div>
  <div class="card-body">
    <div class="cui-gallery">
      <div
        class="cui-gallery-item"
        *ngFor="let image of galleryData"
        [ngStyle]="{'background-image': 'url(' + image.path + ')'}"
        [ngClass]="[image.editable ? 'cui-gallery-with-controls' : '']"
      >
        <div
          *ngIf="image.editable"
          class="cui-gallery-item-controls"
        >
          <nz-button-group>
            <button nz-button><i nz-icon type="edit" theme="outline"></i></button>
            <button nz-button><i nz-icon type="delete" theme="outline"></i></button>
          </nz-button-group>
        </div>
      </div>
    </div>
  </div>
</div>

// cleanui-admin-template-vue/src/views/apps/gallery/index.vue
<template>
  <div class="card">
    <div class="card-header clearfix">
      <div class="pull-right">
        <a-upload
          name="file"
          :multiple="true"
          action="//jsonplaceholder.typicode.com/posts/"
          @change="handleChange"
        >
          <a-button>
            <a-icon type="upload"/>Click to Upload
          </a-button>
        </a-upload>
      </div>
      <div class="utils__title">
        <strong>Photo Gallery</strong>
      </div>
    </div>
    <div class="card-body">
      <div :class="$style.gallery">
        <div
          v-for="(image, index) in images"
          :key="index"
          :class="[$style.item, image.editable === true ? $style.withControls : '']"
          :style="{ backgroundImage: 'url(' + image.path + ')'}"
        >
          <div :class="$style.itemControls" v-if="image.editable">
            <a-button-group>
              <a-button icon="edit"/>
              <a-button icon="delete"/>
            </a-button-group>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import { images } from './data.json'

export default {
  data: function () {
    return {
      images,
    }
  },
  methods: {
    handleChange(info) {
      if (info.file.status !== 'uploading') {
        console.log(info.file, info.fileList)
      }
      if (info.file.status === 'done') {
        this.$message.success(`${info.file.name} file uploaded successfully`)
      } else if (info.file.status === 'error') {
        this.$message.error(`${info.file.name} file upload failed.`)
      }
    },
  },
}
</script>

<style lang="scss" module>
@import "./style.module.scss";
</style>
