// cleanui-admin-template-react-umi-seed/src/components/LayoutComponents/TopBar/ProfileMenu/index.js
import React from 'react'
import { connect } from 'dva'
import { Menu, Dropdown, Avatar, Badge } from 'antd'
import { formatMessage } from 'umi/locale'
import styles from './style.module.scss'

@connect(({ user }) => ({ user }))
class ProfileMenu extends React.Component {
  state = {
    count: 7,
  }

  logout = () => {
    const { dispatch } = this.props
    dispatch({
      type: 'user/LOGOUT',
    })
  }

  addCount = () => {
    let { count } = this.state
    count += 1
    this.setState({
      count,
    })
  }

  render() {
    const { user } = this.props
    const { count } = this.state
    const menu = (
      <Menu selectable={false}>
        <Menu.Item>
          <strong>
            {formatMessage({ id: 'topBar.profileMenu.hello' })}, {user.name || 'Anonymous'}
          </strong>
          <div>
            <strong className="mr-1">
              {formatMessage({ id: 'topBar.profileMenu.billingPlan' })}:
            </strong>
            Professional
          </div>
          <div>
            <strong className="mr-1">{formatMessage({ id: 'topBar.profileMenu.role' })}:</strong>
            {user.role}
          </div>
        </Menu.Item>
        <Menu.Divider />
        <Menu.Item>
          <div>
            <strong className="mr-1">{formatMessage({ id: 'topBar.profileMenu.email' })}:</strong>
            {user.email}
            <br />
            <strong className="mr-1">{formatMessage({ id: 'topBar.profileMenu.phone' })}:</strong>
            {user.phone || '-'}
          </div>
        </Menu.Item>
        <Menu.Divider />
        <Menu.Item>
          <a href="javascript: void(0);">
            <i className={`${styles.menuIcon} icmn-user`} />
            {formatMessage({ id: 'topBar.profileMenu.editProfile' })}
          </a>
        </Menu.Item>
        <Menu.Divider />
        <Menu.Item>
          <a href="javascript: void(0);" onClick={this.logout}>
            <i className={`${styles.menuIcon} icmn-exit`} />
            {formatMessage({ id: 'topBar.profileMenu.logout' })}
          </a>
        </Menu.Item>
      </Menu>
    )
    return (
      <Dropdown overlay={menu} trigger={['click']} onVisibleChange={this.addCount}>
        <div className={styles.dropdown}>
          <Badge count={count}>
            <Avatar className={styles.avatar} shape="square" size="large" icon="user" />
          </Badge>
        </div>
      </Dropdown>
    )
  }
}

export default ProfileMenu

// cleanui-admin-template-vue-seed/src/components/LayoutComponents/Topbar/ProfileMenu/index.vue
<template>
  <a-dropdown :trigger="['click']" placement="bottomLeft" @visibleChange="addCount">
    <div :class="$style.dropdown">
      <a-badge :count="count">
        <a-avatar shape="square" icon="user" size="large" :class="$style.avatar"/>
      </a-badge>
    </div>
    <a-menu slot="overlay">
      <a-menu-item>
        <div>
          <strong>Hello, Administrator</strong>
        </div>
        <div>
          <strong class="mr-1">Billing Plan:</strong> Professional
        </div>
        <div>
          <strong class="mr-1">Role:</strong> Admin
        </div>
      </a-menu-item>
      <a-menu-divider/>
      <a-menu-item>
        <div>
          <strong class="mr-1">Email:</strong> admin@mediatec.org
        </div>
        <div>
          <strong class="mr-1">Phone:</strong> -
        </div>
      </a-menu-item>
      <a-menu-divider/>
      <a-menu-item>
        <a href="javascript: void(0);">
          <i :class="$style.menuIcon" class="icmn-user"></i> Edit Profile
        </a>
      </a-menu-item>
      <a-menu-item>
        <a href="javascript: void(0);" @click="logout">
          <i :class="$style.menuIcon" class="icmn-exit"></i> Logout
        </a>
      </a-menu-item>
    </a-menu>
  </a-dropdown>
</template>

<script>
export default {
  data: function () {
    return {
      count: 7,
    }
  },
  methods: {
    addCount() {
      this.count++
    },
    logout() {
      this.$auth.logout()
    },
  },
}
</script>

<style lang="scss" module>
@import "./style.module.scss";
</style>
