// cleanui-admin-template-react-umi/src/pages/youtube/view/index.js
import React from 'react'
import { Checkbox, Dropdown, Icon, Menu, Input, Button } from 'antd'
import { Helmet } from 'react-helmet'
import Avatar from '@/components/CleanUIComponents/Avatar'
import styles from './style.module.scss'
import data from './data.json'

const { TextArea } = Input

const actions = (
  <Menu>
    <Menu.Item>
      <Icon type="edit" /> Edit Post
    </Menu.Item>
    <Menu.Item>
      <Icon type="delete" /> Delete Post
    </Menu.Item>
    <Menu.Item>
      <Icon type="frown-o" /> Mark as a Spam
    </Menu.Item>
  </Menu>
)

class YouTubeView extends React.Component {
  state = {
    viewData: data.viewData,
    upNext: data.upNext,
  }

  render() {
    const { viewData, upNext } = this.state
    return (
      <div>
        <Helmet title="YouTube View" />
        <section className="card">
          <div className="card-header">
            <div className="utils__title">
              <strong>YouTube View</strong>
            </div>
          </div>
          <div className="card-body">
            <div className={`${styles.videoPage} clearfix`}>
              <div className={styles.mainContent}>
                <div className={styles.player}>
                  <img src="resources/images/photos/4.jpeg" alt="" />
                </div>
                <div className={styles.descr}>
                  <div className={styles.card}>
                    <div className="mb-2">
                      <strong>
                        Published on <span>{viewData.date}</span>
                      </strong>
                      <div className="pull-right">
                        <Dropdown overlay={actions}>
                          <a className="ant-dropdown-link" href="javascript: void(0);">
                            Actions <Icon type="down" />
                          </a>
                        </Dropdown>
                      </div>
                    </div>
                    <p className="mb-0">{viewData.description}</p>
                  </div>
                </div>
                <div>
                  <div className={styles.card}>
                    <div className={styles.addComment}>
                      <div className={styles.commentUser}>
                        <Avatar size="50" src={viewData.accountImg} />
                      </div>
                      <div className={styles.commentForm}>
                        <TextArea rows={3} placeholder="Write a comment..." />
                        <div className="mt-3">
                          <Button className="mr-2" type="primary" style={{ width: 200 }}>
                            <i className="fa fa-send mr-2" />
                            Send
                          </Button>
                        </div>
                      </div>
                    </div>
                    <div>
                      {viewData.comments.map(comment => (
                        <div className={`${styles.commentItem} clearfix`} key={Math.random()}>
                          <div className={styles.commentAvatar}>
                            <Avatar src={comment.avatar} size="50" border="false" />
                          </div>
                          <div className={styles.commentContent}>
                            <strong>
                              {comment.name}
                              <span className={`${styles.commentTime}text-muted ml-2`}>
                                {comment.date}
                              </span>
                            </strong>
                            <p className="mb-0">{comment.content}</p>
                            <div className={styles.commentLike}>
                              <a className="mr-2" href="javascript: void(0);">
                                <i className="icmn-heart mr-2" />
                                {comment.likesCount > 0 && (
                                  <span>{`${comment.likesCount} Likes`}</span>
                                )}
                                {comment.likesCount === 0 && (
                                  <span>{`${comment.likesCount} Like`}</span>
                                )}
                              </a>
                            </div>
                          </div>
                        </div>
                      ))}
                    </div>
                  </div>
                </div>
              </div>
              <div className={`${styles.sidebar} ${styles.card}`}>
                <div className={styles.sidebarHead}>
                  <strong className={styles.sidebarTitle}>Up next</strong>
                  <div className="pull-right">
                    <Checkbox>Autoplay</Checkbox>
                  </div>
                </div>
                <ul className={styles.watchNext}>
                  {upNext.map(video => (
                    <li className={`${styles.nextItem} clearfix`} key={Math.random()}>
                      <a href="javascript: void(0);" className={styles.nextItemLink}>
                        <div className={styles.itemThumb}>
                          <img className={styles.itemThumbImg} src={video.cover} alt={video.name} />
                        </div>
                        <div className={styles.itemDescr}>
                          <span className={styles.itemName}>{video.name}</span>
                          <span className={styles.itemAuthor}>{video.author}</span>
                          <span className={`${styles.itemViews} text-muted`}>
                            <span className={styles.itemCount}>{video.views}</span>
                            views
                          </span>
                        </div>
                      </a>
                    </li>
                  ))}
                </ul>
              </div>
            </div>
          </div>
        </section>
      </div>
    )
  }
}

export default YouTubeView

// cleanui-admin-template-vue/src/views/youtube/view/index.vue
<template>
  <section class="card">
    <div class="card-header">
      <div class="utils__title">
        <strong>YouTube View</strong>
      </div>
    </div>
    <div class="card-body">
      <div :class="$style.videoPage" class="clearfix">
        <div :class="$style.mainContent">
          <div :class="$style.player">
            <img src="resources/images/photos/4.jpeg">
          </div>
          <div :class="$style.descr">
            <div :class="$style.card">
              <div class="mb-2">
                <strong>
                  Published on
                  <span>{{viewData.date}}</span>
                </strong>
                <div class="pull-right">
                  <a-dropdown>
                    <a class="ant-dropdown-link" href="javascript: void(0);">Actions
                      <a-icon type="down"/>
                    </a>
                    <a-menu slot="overlay">
                      <a-menu-item>
                        <a href="javascript:void(0)">
                          <a-icon type="edit"/>Edit Post
                        </a>
                      </a-menu-item>
                      <a-menu-item>
                        <a href="javascript:void(0)">
                          <a-icon type="delete"/>Delete Post
                        </a>
                      </a-menu-item>
                      <a-menu-item>
                        <a href="javascript:void(0)">
                          <a-icon type="frown-o"/>Mark as a Spam
                        </a>
                      </a-menu-item>
                    </a-menu>
                  </a-dropdown>
                </div>
              </div>
              <p class="mb-0">{{viewData.description}}</p>
            </div>
          </div>
          <div :class="$style.card">
            <div :class="$style.addComment">
              <div :class="$style.commentUser">
                <cui-avatar :src="viewData.accountImg" :size="50" :bordered="false"/>
              </div>
              <div :class="$style.commentForm">
                <a-textarea placeholder="Write a comment..." :rows="3"/>
                <div class="mt-3">
                  <a-button class="mr-2" type="primary" style="width: 200px;">
                    <i class="fa fa-send mr-2"></i>
                    Send
                  </a-button>
                </div>
              </div>
            </div>
            <div
              :class="$style.commentItem"
              class="clearfix"
              v-for="(comment, index) in viewData.comments"
              :key="index"
            >
              <div :class="$style.commentAvatar">
                <cui-avatar :src="comment.avatar" :size="50" :bordered="false"/>
              </div>
              <div :class="$style.commentContent">
                <strong>
                  {{comment.name}}
                  <span
                    :class="$style.commentTime"
                    class="text-muted ml-2"
                  >{{comment.date}}</span>
                </strong>
                <p class="mb-0">{{comment.content}}</p>
                <div :class="$style.commentLike">
                  <a href="javascript: void(0);" class="mr-2">
                    <i class="icmn-heart mr-2"/>
                    <span v-if="comment.likesCount > 0">{{comment.likesCount}} Likes</span>
                    <span v-if="comment.likesCount === 0">{{comment.likesCount}} Like</span>
                  </a>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div :class="[$style.sidebar, $style.card]">
          <div :class="$style.sidebarHead">
            <strong :class="$style.sidebarTitle">Up next</strong>
            <div class="pull-right">
              <a-checkbox>Autoplay</a-checkbox>
            </div>
          </div>
          <ul :class="$style.watchNext">
            <li
              :class="$style.nextItem"
              class="clearfix"
              v-for="(video, index) in upNext"
              :key="index"
            >
              <a href="javascript: void(0);" :class="$style.nextItemLink">
                <div :class="$style.itemThumb">
                  <img :src="video.cover" :alt="video.name" :class="$style.itemThumbImg">
                </div>
                <div :class="$style.itemDescr">
                  <span :class="$style.itemName">{{video.name}}</span>
                  <span :class="$style.itemAuthor">{{video.author}}</span>
                  <span :class="$style.itemViews" class="text-muted">
                    <span :class="$style.itemCount">{{video.views}}</span> views
                  </span>
                </div>
              </a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </section>
</template>

<script>
import CuiAvatar from '@/components/CleanUIComponents/Avatar'
import { viewData, upNext } from './data.json'

export default {
  components: {
    CuiAvatar,
  },
  data: function () {
    return {
      viewData,
      upNext,
    }
  },
}
</script>

<style lang="scss" module>
@import "./style.module.scss";
</style>
