// cleanui-admin-template-vue-seed/src/views/dashboard/alpha/index.vue
<template>
  <div>
    <div class="utils__title mb-3">
      <strong class="text-uppercase font-size-16">Empty Page</strong>
    </div>
    <div class="row">
      <div class="col-lg-12">
        <div class="card">
          <div class="card-body">
            [src\views\dashboard\alpha]
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

// cleanui-admin-template-react-cra-seed/src/pages/dashboard/alpha/index.js
import React from 'react'
import { Helmet } from 'react-helmet'
import Authorize from 'components/LayoutComponents/Authorize'

class DashboardAlpha extends React.Component {
  render() {
    return (
      <Authorize roles={['admin','technican','Manager','Office']} redirect to="/dashboard/beta">
        <Helmet title="Home Page" />
        <div className="utils__title utils__title--flat mb-3">
          <strong className="text-uppercase font-size-16">Home Page</strong>
        </div>
        <div className="row">
          <div className="col-lg-12">
            <div className="card">
              <div className="card-body">
                [src\pages\dashboard\alpha\index.js]
              </div>
            </div>
          </div>
        </div>
      </Authorize>
    )
  }
}

export default DashboardAlpha
