// cleanui-admin-template-vue/src/views/pages/pricing-table/index.vue
<template>
  <div class="mb-5">
    <div :class="$style.pricingTable">
      <cui-pricing-item :class="$style.pricingTableItem" type="success" :extended="true"/>
      <cui-pricing-item :class="$style.pricingTableItem"/>
      <cui-pricing-item :class="$style.pricingTableItem"/>
      <cui-pricing-item :class="$style.pricingTableItem" type="default" :extended="true"/>
    </div>
    <div :class="$style.pricingTable">
      <cui-pricing-item :class="$style.pricingTableItem" type="warning"/>
      <cui-pricing-item :class="$style.pricingTableItem"/>
      <cui-pricing-item :class="$style.pricingTableItem" :extended="true"/>
      <cui-pricing-item :class="$style.pricingTableItem"/>
    </div>
  </div>
</template>

<script>
import CuiPricingItem from '@/components/CleanUIComponents/PricingItem'

export default {
  components: {
    CuiPricingItem,
  },
}
</script>

<style lang="scss" module>
@import "./style.module.scss";
</style>

// cleanui-admin-template-react-umi/src/pages/pages/pricing-table/index.js
import React from 'react'
import { Helmet } from 'react-helmet'
import PricingItem from '@/components/CleanUIComponents/PricingItem'
import styles from './style.module.scss'

class PricingTable extends React.Component {
  render() {
    return (
      <div>
        <Helmet title="Pricing Table" />
        <div className="mb-5">
          <div className={styles.pricingTable}>
            <PricingItem type="success" extended />
            <PricingItem />
            <PricingItem />
            <PricingItem type="default" />
          </div>
          <div className={styles.pricingTable}>
            <PricingItem type="warning" />
            <PricingItem />
            <PricingItem extended />
            <PricingItem />
          </div>
        </div>
      </div>
    )
  }
}

export default PricingTable
