// cleanui-admin-template-vue/src/views/pages/pricing-table/index.vue
<template>
  <div class="mb-5">
    <div :class="$style.pricingTable">
      <cui-pricing-item :class="$style.pricingTableItem" type="success" :extended="true"/>
      <cui-pricing-item :class="$style.pricingTableItem"/>
      <cui-pricing-item :class="$style.pricingTableItem"/>
      <cui-pricing-item :class="$style.pricingTableItem" type="default" :extended="true"/>
    </div>
    <div :class="$style.pricingTable">
      <cui-pricing-item :class="$style.pricingTableItem" type="warning"/>
      <cui-pricing-item :class="$style.pricingTableItem"/>
      <cui-pricing-item :class="$style.pricingTableItem" :extended="true"/>
      <cui-pricing-item :class="$style.pricingTableItem"/>
    </div>
  </div>
</template>

<script>
import CuiPricingItem from '@/components/CleanUIComponents/PricingItem'

export default {
  components: {
    CuiPricingItem,
  },
}
</script>

<style lang="scss" module>
@import "./style.module.scss";
</style>

// cleanui-admin-template-angular/src/app/pages/pages/pricing-table/pricing-table.component.ts
import { Component } from '@angular/core'

@Component({
  selector: 'app-pages-pricing-table',
  templateUrl: './pricing-table.component.html',
  styleUrls: ['./pricing-table.component.scss'],
})
export class PagesPricingTableComponent {}

<div>
  <div class="pricingTable">
    <cui-pricing-item class="pricingTableItem" type="success" [extended]="true"></cui-pricing-item>
    <cui-pricing-item class="pricingTableItem"></cui-pricing-item>
    <cui-pricing-item class="pricingTableItem"></cui-pricing-item>
    <cui-pricing-item class="pricingTableItem" type="default"></cui-pricing-item>
  </div>
  <div class="pricingTable">
    <cui-pricing-item class="pricingTableItem" type="warning"></cui-pricing-item>
    <cui-pricing-item class="pricingTableItem"></cui-pricing-item>
    <cui-pricing-item class="pricingTableItem" [extended]="true"></cui-pricing-item>
    <cui-pricing-item class="pricingTableItem"></cui-pricing-item>
  </div>
</div>
