// cleanui-admin-template-react-umi-seed/src/layouts/Login/index.js
import React from 'react'
import { Layout, Button } from 'antd'
import { Link, withRouter } from 'dva/router'
import styles from './style.module.scss'

@withRouter
class LoginLayout extends React.PureComponent {
  state = {
    backgroundNumber: 1,
    backgroundEnabled: false,
  }

  changeBackground = () => {
    const { backgroundNumber } = this.state
    this.setState({
      backgroundEnabled: true,
      backgroundNumber: backgroundNumber === 5 ? 1 : backgroundNumber + 1,
    })
  }

  toggleBackground = () => {
    const { backgroundEnabled } = this.state
    this.setState({
      backgroundEnabled: !backgroundEnabled,
    })
  }

  render() {
    const { children } = this.props
    const { backgroundNumber, backgroundEnabled } = this.state

    return (
      <Layout>
        <Layout.Content>
          <div
            className={backgroundEnabled ? `${styles.layout} ${styles.light}` : `${styles.layout}`}
            style={{
              backgroundImage: backgroundEnabled
                ? `url('resources/images/photos/${backgroundNumber}.jpeg')`
                : `none`,
            }}
          >
            <div className={styles.header}>
              <div className={styles.logo}>
                <Link to="/">
                  {!backgroundEnabled && (
                    <img src="resources/images/logo.png" alt="Clean UI React Admin Template" />
                  )}
                  {backgroundEnabled && (
                    <img
                      src="resources/images/logo-inverse.png"
                      alt="Clean UI React Admin Template"
                    />
                  )}
                </Link>
              </div>
              <div className={styles.controls}>
                <div className="d-inline-block mr-3">
                  <Button type="default" onClick={this.changeBackground}>
                    Change Background
                  </Button>
                </div>
                <div className="d-inline-block">
                  <Button type="default" onClick={this.toggleBackground}>
                    Toggle Background
                  </Button>
                </div>
              </div>
              <nav className={styles.navigation}>
                <ul className={styles.navigationItems}>
                  <li>
                    <a href="javascript: void(0);">&larr; Back</a>
                  </li>
                  <li>
                    <a className={styles.navigationActive} href="javascript: void(0);">
                      Login
                    </a>
                  </li>
                  <li>
                    <a href="javascript: void(0);">About</a>
                  </li>
                  <li>
                    <a href="javascript: void(0);">Support</a>
                  </li>
                </ul>
              </nav>
            </div>
            <div className={styles.content}>{children}</div>
            <div className={`${styles.footer} text-center`}>
              <ul className="list-unstyled list-inline mb-3">
                <li className="list-inline-item">
                  <a href="javascript: void(0);">Terms of Use</a>
                </li>
                <li className="active list-inline-item">
                  <a href="javascript: void(0);">Compliance</a>
                </li>
                <li className="list-inline-item">
                  <a href="javascript: void(0);">Confidential Information</a>
                </li>
                <li className="list-inline-item">
                  <a href="javascript: void(0);">Support</a>
                </li>
                <li className="list-inline-item">
                  <a href="javascript: void(0);">Contacts</a>
                </li>
              </ul>
              <p>&copy; 2019 Mediatec. All rights reserved.</p>
            </div>
          </div>
        </Layout.Content>
      </Layout>
    )
  }
}

export default LoginLayout

// cleanui-admin-template-vue/src/layouts/Login/index.vue
<template>
  <a-layout>
    <a-layout-content>
      <div
        :class="[$style.layout, backgroundEnabled ? $style.light : '']"
        :style="{backgroundImage: backgroundEnabled ? `url(\'resources/images/photos/${backgroundNumber}.jpeg\')` : 'none'}"
      >
        <div :class="$style.header">
          <div :class="$style.logo">
            <router-link to="/">
              <img
                v-if="!backgroundEnabled"
                src="resources/images/logo.png"
                alt="Clean UI Admin Template"
              >
              <img
                v-if="backgroundEnabled"
                src="resources/images/logo-inverse.png"
                alt="Clean UI Admin Template"
              >
            </router-link>
          </div>
          <div :class="$style.controls">
            <div class="d-inline-block mr-3">
              <a-button type="default" @click="changeBackground">Change Background</a-button>
            </div>
            <div class="d-inline-block">
              <a-button type="default" @click="toggleBackground">Toggle Background</a-button>
            </div>
          </div>
          <nav :class="$style.navigation">
            <ul :class="$style.navigationItems">
              <li>
                <a href="javascript: void(0);">&larr; Back</a>
              </li>
              <li>
                <a :class="$style.navigationActive" href="javascript: void(0);">Login</a>
              </li>
              <li>
                <a href="javascript: void(0);">About</a>
              </li>
              <li>
                <a href="javascript: void(0);">Support</a>
              </li>
            </ul>
          </nav>
        </div>
        <div :class="$style.content">
          <router-view/>
        </div>
        <div :class="[$style.footer, 'text-center']">
          <ul class="list-unstyled list-inline mb-3">
            <li class="list-inline-item">
              <a href="javascript: void(0);">Terms of Use</a>
            </li>
            <li class="active list-inline-item">
              <a href="javascript: void(0);">Compliance</a>
            </li>
            <li class="list-inline-item">
              <a href="javascript: void(0);">Confidential Information</a>
            </li>
            <li class="list-inline-item">
              <a href="javascript: void(0);">Support</a>
            </li>
            <li class="list-inline-item">
              <a href="javascript: void(0);">Contacts</a>
            </li>
          </ul>
          <p>&copy; 2019 Mediatec. All rights reserved.</p>
        </div>
      </div>
    </a-layout-content>
  </a-layout>
</template>

<script>
export default {
  name: 'LoginLayout',
  data: function () {
    return {
      backgroundEnabled: false,
      backgroundNumber: 1,
    }
  },
  methods: {
    changeBackground() {
      this.backgroundEnabled = true
      if (this.backgroundNumber === 5) {
        this.backgroundNumber = 1
      } else {
        this.backgroundNumber += 1
      }
    },
    toggleBackground() {
      this.backgroundEnabled = !this.backgroundEnabled
    },
  },
}
</script>

<style lang="scss" module>
@import "./style.module.scss";
</style>
