// cleanui-admin-template-angular/src/app/pages/ecommerce/cart/cart.component.ts
import { Component } from '@angular/core'
declare var require: any
const data: any = require('./data.json')

@Component({
  selector: 'app-ecommerce-cart',
  templateUrl: './cart.component.html',
  styleUrls: ['./cart.component.scss'],
})
export class EcommerceCartComponent {
  ordersTableData = data.ordersTableData
  invoicePrices = data.invoicePrices
  current = 0

  pre(): void {
    this.current -= 1
    // this.changeContent();
  }

  next(): void {
    this.current += 1
    // this.changeContent();
  }

  done(): void {
    console.log('done')
  }
}

<div class="card">
  <div class="card-body">
    <div class="cui-cart">
      <div class="cui-cart-steps">
        <nz-steps [nzCurrent]="current">
          <nz-step nzTitle="Cart" nzIcon="shopping-cart" class="cui-cart-step"></nz-step>
          <nz-step nzTitle="Shipment and Payment" nzIcon="tags" class="cui-cart-step"></nz-step>
          <nz-step nzTitle="Confirmation" nzIcon="credit-card" class="cui-cart-step"></nz-step>
        </nz-steps>
      </div>
      <div class="cui-cart-steps-content">
        <div *ngIf="current === 0">
          <nz-table #ordersTable [nzShowPagination]="false" [nzData]="ordersTableData" class="utils__scrollTable" [nzScroll]="{x: '100%'}">
            <thead>
              <tr>
                <th>#</th>
                <th>Description</th>
                <th>Quantity</th>
                <th>Unitcost</th>
                <th>Total</th>
                <th></th>
              </tr>
            </thead>
            <tbody>
            <tr *ngFor="let item of ordersTable.data">
              <td>{{item.number}}</td>
              <td>
                <a class="utils__link--underlined" href="javascript: void(0);">
                  {{item.description}}
                </a>
              </td>
              <td>
                <nz-input-number [(ngModel)]="item.quantity" [nzMin]="1" [nzStep]="1"></nz-input-number>
              </td>
              <td>{{item.unitcost}}</td>
              <td>{{item.total}}</td>
              <td>
                <button nz-button><i nz-icon type="delete"></i> Remove</button>
              </td>
            </tr>
            </tbody>
          </nz-table>
          <div class="text-right clearfix mt-4">
            <div class="pull-right">
              <p>
                Sub - Total amount:
                <strong>
                  <span>{{invoicePrices.invoiceAmount}}</span>
                </strong>
              </p>
              <p>
                VAT:
                <strong>
                  <span>{{invoicePrices.invoiceVAT}}</span>
                </strong>
              </p>
              <p>
                <strong>
                  Grand Total: <span>{{invoicePrices.invoiceTotal}}</span>
                </strong>
              </p>
              <br />
            </div>
          </div>
        </div>
        <div *ngIf="current === 1">
          <div class="row">
            <div class="col-md-8">
              <h4 class="text-black mb-3">
                <strong>Shipment Details</strong>
              </h4>
              <form nz-form nzLayout="vertical">
                <div class="row">
                  <div class="col-md-6">
                    <nz-form-item>
                      <nz-form-label nzFor="email" nzRequired>Email</nz-form-label>
                      <nz-form-control>
                        <input nz-input id="email" placeholder="Email">
                      </nz-form-control>
                    </nz-form-item>
                  </div>
                  <div class="col-md-6">
                    <nz-form-item>
                      <nz-form-label nzFor="phone" nzRequired>Phone Number</nz-form-label>
                      <nz-form-control>
                        <input nz-input id="phone" placeholder="Phone Number">
                      </nz-form-control>
                    </nz-form-item>
                  </div>
                  <div class="col-md-6">
                    <nz-form-item>
                      <nz-form-label nzFor="name" nzRequired>Name</nz-form-label>
                      <nz-form-control>
                        <input nz-input id="name" placeholder="Name">
                      </nz-form-control>
                    </nz-form-item>
                  </div>
                  <div class="col-md-6">
                    <nz-form-item>
                      <nz-form-label nzFor="surname" nzRequired>Surname</nz-form-label>
                      <nz-form-control>
                        <input nz-input id="surname" placeholder="Surname">
                      </nz-form-control>
                    </nz-form-item>
                  </div>
                  <div class="col-md-12">
                    <nz-form-item>
                      <nz-form-label nzFor="city" nzRequired>City</nz-form-label>
                      <nz-form-control>
                        <input nz-input id="city" placeholder="City">
                      </nz-form-control>
                    </nz-form-item>
                  </div>
                  <div class="col-md-12">
                    <nz-form-item>
                      <nz-form-label nzFor="adress" nzRequired>Adress</nz-form-label>
                      <nz-form-control>
                        <input nz-input id="adress" placeholder="Adress">
                      </nz-form-control>
                    </nz-form-item>
                  </div>
                </div>
                <h4 class="text-black mb-3">
                  <strong>Billing Details</strong>
                </h4>
                <div class="row">
                  <div class="col-md-12">
                    <nz-form-item>
                      <nz-form-label nzFor="cardNum" nzRequired>Card Number</nz-form-label>
                      <nz-input-group [nzAddOnBefore]="addOnCardNum">
                        <input type="text" nz-input [(ngModel)]="inputValue" placeholder="Card Number">
                      </nz-input-group>
                      <ng-template #addOnCardNum>
                        <i nz-icon type="credit-card" theme="outline"></i>
                      </ng-template>
                    </nz-form-item>
                  </div>
                  <div class="col-md-6">
                    <nz-form-item>
                      <nz-form-label nzFor="expDate" nzRequired>Expiration Date</nz-form-label>
                      <nz-form-control>
                        <input nz-input id="expDate" placeholder="MM / YY">
                      </nz-form-control>
                    </nz-form-item>
                  </div>
                  <div class="col-md-6">
                    <nz-form-item>
                      <nz-form-label nzFor="cvc" nzRequired>Card CVC</nz-form-label>
                      <nz-form-control>
                        <input nz-input id="cvc" placeholder="CVC">
                      </nz-form-control>
                    </nz-form-item>
                  </div>
                  <div class="col-md-12">
                    <nz-form-item>
                      <nz-form-label nzFor="cardName" nzRequired>Card Holder Name</nz-form-label>
                      <nz-form-control>
                        <input nz-input id="cardName" placeholder="Name and Surname">
                      </nz-form-control>
                    </nz-form-item>
                  </div>
                </div>
              </form>
            </div>
            <div class="col-md-4">
              <h4 class="text-black mb-3">
                <strong>General Info</strong>
              </h4>
              <h2>
                <i class="fa fa-cc-visa text-primary mr-1"></i>
                <i class="fa fa-cc-mastercard text-default mr-1"></i>
                <i class="fa fa-cc-amex text-default"></i>
              </h2>
              <p>
                Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor
                incididunt ut labore et dolore magna aliqua.
              </p>
              <p>
                Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip
                ex ea commodo consequat.
              </p>
            </div>
          </div>
        </div>
        <div *ngIf="current === 2">
          <cui-invoice></cui-invoice>
        </div>
      </div>
      <div class="cui-cart-steps-action">
        <button nz-button nzType="default" (click)="pre()" *ngIf="current > 0">
          <span>Previous</span>
        </button>
        <button nz-button nzType="default" (click)="next()" *ngIf="current < 2">
          <span>Next</span>
        </button>
        <button nz-button nzType="primary" (click)="done()" *ngIf="current === 2">
          <span>Done</span>
        </button>
      </div>
    </div>
  </div>
</div>

// cleanui-admin-template-vue/src/views/ecommerce/cart/index.vue
<template>
  <div class="card">
    <div class="card-body">
      <a-steps :current="current">
        <a-step title="Cart">
          <a-icon type="user" style="font-size: 40px;" slot="icon"/>Cart
        </a-step>
        <a-step title="Shipment and Payment">
          <a-icon type="tags" style="font-size: 40px;" slot="icon"/>Cart
        </a-step>
        <a-step title="Confirmation">
          <a-icon type="credit-card" style="font-size: 40px;" slot="icon"/>Cart
        </a-step>
      </a-steps>
      <div :class="$style.stepsContent">
        <div v-if="current === 0">
          <a-table
            :columns="columns"
            :dataSource="ordersTableData"
            :pagination="false"
            class="utils__scrollTable"
            :scroll="{ x: '100%' }"
          >
            <a
              href="javascript: void(0);"
              slot="description"
              slot-scope="text"
              class="utils__link"
            >{{text}}</a>
            <a-input-number
              slot="quantity"
              slot-scope="value"
              size="small"
              :min="1"
              :defaultValue="+value"
            />
            <a-button size="small" slot="actions">
              <a-icon type="cross"/>Remove
            </a-button>
          </a-table>
          <div class="text-right clearfix mt-4">
            <div class="pull-right">
              <p>
                Sub - Total amount:
                <strong>
                  <span>{{invoicePrices.invoiceAmount}}</span>
                </strong>
              </p>
              <p>
                VAT:
                <strong>
                  <span>{{invoicePrices.invoiceVAT}}</span>
                </strong>
              </p>
              <p>
                <strong>
                  Grand Total:
                  <span>{{invoicePrices.invoiceTotal}}</span>
                </strong>
              </p>
              <br>
            </div>
          </div>
        </div>
        <div v-if="current === 1">
          <div class="row">
            <div class="col-md-8">
              <h4 class="text-black mb-3">Shipment Details</h4>
              <a-form :form="form">
                <div class="row">
                  <div class="col-md-6">
                    <a-form-item label="Email">
                      <a-input
                        placeholder="Email"
                        v-decorator="['email', {rules: [{required: true, message: 'Please input your Email!'}]}]"
                      />
                    </a-form-item>
                  </div>
                  <div class="col-md-6">
                    <a-form-item label="Phone Number">
                      <a-input
                        placeholder="Phone Number"
                        v-decorator="['phoneNumber', {rules: [{required: true, message: 'Please input your Phone Number!'}]}]"
                      />
                    </a-form-item>
                  </div>
                  <div class="col-md-6">
                    <a-form-item label="Name">
                      <a-input
                        placeholder="Name"
                        v-decorator="['name', {rules: [{required: true, message: 'Please input your Name!'}]}]"
                      />
                    </a-form-item>
                  </div>
                  <div class="col-md-6">
                    <a-form-item label="Surname">
                      <a-input
                        placeholder="Surname"
                        v-decorator="['surname', {rules: [{required: true, message: 'Please input your Surname!'}]}]"
                      />
                    </a-form-item>
                  </div>
                  <div class="col-md-12">
                    <a-form-item label="City">
                      <a-input
                        placeholder="City"
                        v-decorator="['city', {rules: [{required: true, message: 'Please input your City!'}]}]"
                      />
                    </a-form-item>
                  </div>
                  <div class="col-md-12 mb-3">
                    <a-form-item label="Adress">
                      <a-input
                        placeholder="Adress"
                        v-decorator="['city', {rules: [{required: true, message: 'Please input your Adress!'}]}]"
                      />
                    </a-form-item>
                  </div>
                  <div class="col-12">
                    <h4 class="text-black mb-3">
                      <strong>Billing Details</strong>
                    </h4>
                  </div>
                  <div class="col-md-12">
                    <a-form-item label="Card Number">
                      <a-input
                        placeholder="Card Number"
                        v-decorator="['curdnum', {rules: [{required: true, message: 'Please input your Card Number!'}]}]"
                      >
                        <a-icon type="credit-card" slot="addonBefore"/>
                      </a-input>
                    </a-form-item>
                  </div>
                  <div class="col-md-7">
                    <a-form-item label="Expiration Date">
                      <a-input
                        placeholder="Surname"
                        v-decorator="['expirationdate', {rules: [{required: true, message: 'Please input Card Expiration Date!'}]}]"
                      />
                    </a-form-item>
                  </div>
                  <div class="col-md-5">
                    <a-form-item label="Card CVC">
                      <a-input
                        placeholder="CVC"
                        v-decorator="['cardcvc', {rules: [{required: true, message: 'Please input Card CVC!'}]}]"
                      />
                    </a-form-item>
                  </div>
                  <div class="col-md-12">
                    <a-form-item label="Card Holder Name">
                      <a-input
                        placeholder="Name and Surname"
                        v-decorator="['cardholdername', {rules: [{required: true, message: 'Please input Card Holder Name!'}]}]"
                      />
                    </a-form-item>
                  </div>
                </div>
              </a-form>
            </div>
            <div class="col-md-4">
              <h4 class="text-black mb-3">
                <strong>General Info</strong>
              </h4>
              <h2>
                <i class="fa fa-cc-visa text-primary mr-1"/>
                <i class="fa fa-cc-mastercard text-default mr-1"/>
                <i class="fa fa-cc-amex text-default"/>
              </h2>
              <p>
                Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor
                incididunt ut labore et dolore magna aliqua.
              </p>
              <p>
                Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip
                ex ea commodo consequat.
              </p>
            </div>
          </div>
        </div>
        <div v-if="current === 2">
          <cui-invoice/>
        </div>
      </div>
      <div class="text-center" :class="$style.stepsAction">
        <a-button v-if="current > 0" style="margin-left: 8px" @click="prev" class="mr-2">Previous</a-button>
        <a-button v-if="current < 2" type="primary" @click="next">Next</a-button>
      </div>
    </div>
  </div>
</template>

<script>
import { ordersTableData, invoicePrices } from './data.json'
import CuiInvoice from '@/components/CleanUIComponents/Invoice'

const columns = [
  {
    title: '#',
    dataIndex: 'number',
  },
  {
    title: 'Description',
    dataIndex: 'description',
    scopedSlots: { customRender: 'description' },
  },
  {
    title: 'Quantity',
    dataIndex: 'quantity',
    scopedSlots: { customRender: 'quantity' },
  },
  {
    title: 'Unit Cost',
    dataIndex: 'unitcost',
  },
  {
    title: 'Total',
    dataIndex: 'total',
  },
  {
    title: '',
    dataIndex: '',
    scopedSlots: { customRender: 'actions' },
  },
]
export default {
  components: {
    CuiInvoice,
  },
  data: function () {
    return {
      ordersTableData,
      invoicePrices,
      current: 0,
      columns,
      form: this.$form.createForm(this),
    }
  },
  methods: {
    next() {
      this.current++
    },
    prev() {
      this.current--
    },
  },
}
</script>

<style lang="scss" module>
@import "./style.module.scss";
</style>
