// cleanui-admin-template-vue/src/views/github/explore/index.vue
<template>
  <section class="card">
    <div class="card-header">
      <div class="utils__title">
        <strong>GitHub Explore</strong>
      </div>
    </div>
    <div class="card-body">
      <div :class="$style.explore">
        <div class="mb-3">
          <a-tabs defaultActiveKey="1" type="card">
            <a-tab-pane key="1">
              <span slot="tab">
                <i class="mr-2 fa fa-home"/>
                Home
              </span>
            </a-tab-pane>
            <a-tab-pane key="2">
              <span slot="tab">
                <i class="mr-2 fa fa-comments"/>
                Discussion
              </span>
            </a-tab-pane>
            <a-tab-pane key="3">
              <span slot="tab">
                <i class="mr-2 fa fa-user"/>
                Profile
              </span>
            </a-tab-pane>
            <a-tab-pane key="4">
              <span slot="tab">
                <i class="mr-2 fa fa-envelope"/>
                Messages
              </span>
            </a-tab-pane>
            <a-tab-pane key="5">
              <span slot="tab">
                <i class="mr-2 fa fa-cog"/>
                Settings
              </span>
            </a-tab-pane>
          </a-tabs>
        </div>
        <div class="clearfix" :class="$style.descr">
          <p :class="$style.descrText">{{projectData.description}}</p>
          <span class="pull-right">
            <a-button>Edit</a-button>
          </span>
        </div>
        <div :class="$style.overallData">
          <ul :class="$style.overallDataList">
            <li :class="$style.overallDataItem">
              <a href="javascript: void(0);">
                <i class="fa fa-check-circle-o mr-2"/>
                {{projectData.commits}} commits
              </a>
            </li>
            <li :class="$style.overallDataItem">
              <a href="javascript: void(0);">
                <i class="fa fa-th-list mr-2"/>
                {{projectData.branches}} branch
              </a>
            </li>
            <li :class="$style.overallDataItem">
              <a href="javascript: void(0);">
                <i class="fa fa-window-maximize mr-2"/>
                {{projectData.releases}} releases
              </a>
            </li>
            <li :class="$style.overallDataItem">
              <a href="javascript: void(0);">
                <i class="fa fa-bell mr-2"/>
                {{projectData.contributors}} contributors
              </a>
            </li>
          </ul>
        </div>
        <div class="clearfix">
          <div :class="$style.sortLeft">
            <a-select
              class="mr-2 mb-2"
              showSearch
              allowClear
              placeholder="Select a type"
              optionFilterProp="children"
              style="width: 200px"
            >
              <a-select-option value="html">HTML</a-select-option>
              <a-select-option value="css">CSS</a-select-option>
              <a-select-option value="javascript">JavaScript</a-select-option>
            </a-select>
            <a-button>New request</a-button>
          </div>
          <div :class="$style.sortRight">
            <div :class="$style.sortOption" class="mr-2 mb-2">
              <a-radio-group>
                <a-radio-button value="create">Create new file</a-radio-button>
                <a-radio-button value="upload">Upload files</a-radio-button>
                <a-radio-button value="find">Find file</a-radio-button>
              </a-radio-group>
            </div>
            <div :class="$style.sortOption" class="mb-2">
              <a-dropdown slot="actions">
                <a-button>Download
                  <a-icon type="down"/>
                </a-button>
                <a-menu slot="overlay">
                  <a-menu-item>
                    <a href="javascript:;">1st menu item</a>
                  </a-menu-item>
                  <a-menu-item>
                    <a href="javascript:;">2nd menu item</a>
                  </a-menu-item>
                  <a-menu-item>
                    <a href="javascript:;">3rd menu item</a>
                  </a-menu-item>
                </a-menu>
              </a-dropdown>
            </div>
          </div>
        </div>
        <div class="table-responsive">
          <table :class="$style.nav" class="table table-hover text-nowrap">
            <tbody>
              <tr v-for="(item, index) in projectData.explore" :key="index">
                <td :class="$style.navIcon">
                  <i :class="[item.type === 'folder' ? 'fa-folder' : 'fa-file-o', 'fa']"/>
                </td>
                <td>
                  <a href="javascript: void(0);">{{item.name}}</a>
                </td>
                <td>{{item.info}}</td>
                <td :class="$style.navTime">{{item.time}}</td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </section>
</template>

<script>
import { projectData } from './data.json'

export default {
  data: function () {
    return {
      projectData,
    }
  },
}
</script>

<style lang="scss" module>
@import "./style.module.scss";
</style>

// cleanui-admin-template-angular/src/app/pages/github/explore/explore.component.ts
import { Component, OnInit } from '@angular/core'
declare var require: any
const data: any = require('./data.json')

@Component({
  selector: 'app-github-explore',
  templateUrl: './explore.component.html',
  styleUrls: ['./explore.component.scss'],
})
export class GithubExploreComponent implements OnInit {
  projectData = data.projectData

  tabs = [
    {
      name: 'Home',
      icon: 'mr-2 fa fa-home',
    },
    {
      name: 'Discussion',
      icon: 'mr-2 fa fa-comments',
    },
    {
      name: 'Profile',
      icon: 'mr-2 fa fa-user',
    },
    {
      name: 'Messages',
      icon: 'mr-2 fa fa-envelope',
    },
    {
      name: 'Settings',
      icon: 'mr-2 fa fa-cog',
    },
  ]

  ngOnInit(): void {}
}

<div class="card">
  <div class="card-header">
    <div class="utils__title">
      <strong>GitHub Explore</strong>
    </div>
  </div>
  <div class="card-body">
    <div class="cui-github-explore-container">
      <div class="mb-3">
        <nz-tabset [nzType]="'card'">
          <nz-tab *ngFor="let tab of tabs" [nzTitle]="titleTemplate">
            <ng-template #titleTemplate>
              <i [class]="tab.icon"></i>{{ tab.name }}
            </ng-template>
          </nz-tab>
        </nz-tabset>
      </div>
      <div class="cui-github-explore-descr clearfix">
        <p class="cui-github-explore-descr-text">{{projectData.description}}</p>
        <span class="pull-right">
          <button nz-button>Edit</button>
        </span>
      </div>
      <div class="cui-github-explore-overall-data">
        <ul class="cui-github-explore-overall-data-list">
          <li class="cui-github-explore-overall-data-item">
            <a href="javascript: void(0);">
              <i class="fa fa-check-circle-o mr-2"></i>
              {{projectData.commits}} commits
            </a>
          </li>
          <li class="cui-github-explore-overall-data-item">
            <a href="javascript: void(0);">
              <i class="fa fa-th-list mr-2"></i>
              {{projectData.branches}} branch
            </a>
          </li>
          <li class="cui-github-explore-overall-data-item">
            <a href="javascript: void(0);">
              <i class="fa fa-window-maximize mr-2"></i>
              {{projectData.releases}} releases
            </a>
          </li>
          <li class="cui-github-explore-overall-data-item">
            <a href="javascript: void(0);">
              <i class="fa fa-bell mr-2"></i>
              {{projectData.contributors}} contributors
            </a>
          </li>
        </ul>
      </div>
      <div class="clearfix">
        <div class="cui-github-explore-sort-left">
          <nz-select style="width: 200px;" nzShowSearch nzAllowClear nzPlaceHolder="Select a type" class="mr-2 mb-2">
            <nz-option nzLabel="HTML" nzValue="HTML"></nz-option>
            <nz-option nzLabel="CSS" nzValue="CSS"></nz-option>
            <nz-option nzLabel="JavaScript" nzValue="JavaScript"></nz-option>
          </nz-select>
          <button nz-button>New request</button>
        </div>
        <div class="cui-github-explore-sort-right">
          <div class="cui-github-explore-sort-option mr-2 mb-2">
            <nz-button-group>
              <button nz-button nzType="default">Create new file</button>
              <button nz-button nzType="default">Upload files</button>
              <button nz-button nzType="default">Find file</button>
            </nz-button-group>
          </div>
          <div class="cui-github-explore-sort-option mb-2">
            <nz-dropdown>
              <button nz-button nz-dropdown><span>Button</span> <i nz-icon type="down"></i></button>
              <ul nz-menu>
                <li nz-menu-item>
                  <a>1st menu item</a>
                </li>
                <li nz-menu-item>
                  <a>2nd menu item</a>
                </li>
                <li nz-menu-item>
                  <a>3rd menu item</a>
                </li>
              </ul>
            </nz-dropdown>
          </div>
        </div>
      </div>
      <div class="table-responsive">
        <table class="table table-hover text-nowrap">
          <tbody>
            <tr *ngFor="let item of projectData.explore">
              <td class="cui-github-explore-nav-icon">
                <i class="fa" [ngClass]="[item.type === 'folder' ? 'fa-folder' : 'fa-file-o']"></i>
              </td>
              <td>
                <a href="javascript: void(0);">
                  {{item.name}}
                </a>
              </td>
              <td>
                {{item.info}}
              </td>
              <td class="cui-github-explore-nav-time">{{item.time}}</td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
