// cleanui-admin-template-react-umi/src/pages/apps/mail/index.js
import React from 'react'
import { Tabs, Input, Icon, Table, Button } from 'antd'
import { Helmet } from 'react-helmet'
import styles from './style.module.scss'
import data from './data.json'

const { TabPane } = Tabs
const { Search } = Input

const mailTab = category => (
  <div className={styles.tab}>
    <div className={styles.tabContent}>
      <div className="mb-1">
        <strong>
          {category.mailCount > 0 ? `${category.title} (${category.mailCount})` : category.title}
        </strong>
      </div>
      {category.mailCount > 0 && (
        <div>
          <small className={styles.tabTime}>8:34PM</small>
          <div className={styles.tabName}>Barak Obama</div>
          <div className={styles.tabText}>
            Hello! Where you are now? I want to talk. Hello! Where you are now? I want to talk
          </div>
        </div>
      )}
    </div>
  </div>
)

class MailList extends React.Component {
  state = {
    mailData: data.mailData,
    mailCategories: data.mailData.mailCategories,
    activeCategory: 'inbox',
    mails: data.mailData.inbox,
  }

  changeCategory = key => {
    const { mailData } = this.state
    const activeCategory = key
    const mails = mailData[activeCategory]

    this.setState({
      activeCategory,
      mails,
    })
  }

  render() {
    const { mailCategories, mails, activeCategory } = this.state

    const columns = [
      {
        title: '',
        dataIndex: 'favorites',
        key: 'favorites',
        render: text => (
          <i
            className={
              text === true ? 'icmn-star-full text-warning' : 'icmn-star-full text-default'
            }
          />
        ),
      },
      {
        title: 'From',
        dataIndex: 'from',
        key: 'from',
        render: text => <a href="javascript: void(0);">{text}</a>,
        sorter: (a, b) => a.from.length - b.from.length,
      },
      {
        title: 'Message',
        dataIndex: 'message',
        key: 'message',
        sorter: (a, b) => a.message.length - b.message.length,
      },
      {
        title: '',
        dataIndex: 'attachments',
        key: 'attachments',
        render: text => {
          if (text === true) {
            return <i className="icmn-attachment text-default" />
          }
          return ''
        },
      },
      {
        title: '',
        dataIndex: 'time',
        key: 'time',
      },
    ]

    return (
      <div>
        <Helmet title="Mail App" />
        <div className={`card ${styles.mail}`}>
          <div className={styles.sidebar}>
            <div className={styles.sidebarHeader}>
              <Search placeholder="input search text" style={{ width: '100%' }} />
            </div>
            <div className={styles.tabs}>
              <Tabs
                defaultActiveKey={activeCategory}
                tabPosition="left"
                onChange={this.changeCategory}
              >
                {mailCategories.map(category => (
                  <TabPane tab={mailTab(category)} key={category.key} />
                ))}
              </Tabs>
            </div>
          </div>
          <div className={styles.content}>
            <div className={styles.contentHeader}>
              <div className="card-header clearfix">
                <div className="pull-right">
                  <Button type="primary">Compose mail</Button>
                </div>
                <Tabs defaultActiveKey="1" tabPosition="top">
                  <TabPane
                    tab={
                      <span>
                        <Icon type="home" /> Primary
                      </span>
                    }
                    key="1"
                  />
                  <TabPane
                    tab={
                      <span>
                        <Icon type="message" /> Social
                      </span>
                    }
                    key="2"
                  />
                  <TabPane
                    tab={
                      <span>
                        <Icon type="tags" /> Promotion
                      </span>
                    }
                    key="3"
                  />
                </Tabs>
              </div>
            </div>
            <div className={styles.contentWrapper}>
              <Table
                className="utils__scrollTable"
                scroll={{ x: '100%' }}
                columns={columns}
                dataSource={mails}
              />
            </div>
          </div>
        </div>
      </div>
    )
  }
}

export default MailList

// cleanui-admin-template-angular/src/app/pages/apps/mail/mail.component.ts
import { Component, OnInit } from '@angular/core'
declare var require: any
const data: any = require('./data.json')

@Component({
  selector: 'app-apps-mail',
  templateUrl: './mail.component.html',
  styleUrls: ['./mail.component.scss'],
})
export class AppsMailComponent implements OnInit {
  mailData = data.mailData
  mailCategories = data.mailData.mailCategories
  activeCategoryIndex = 0
  mail = data.mailData.inbox

  changeMailData(key) {
    this.mail = data.mailData[key]
  }

  ngOnInit() {}
}

<div class="card cui-mail">
  <div class="cui-mail-sidebar">
    <div class="cui-mail-sidebar-header">
      <nz-input-group [nzSuffix]="suffixIconSearch" style="width: 100%">
        <input type="text" nz-input placeholder="Search mail ...">
      </nz-input-group>
      <ng-template #suffixIconSearch>
        <i nz-icon type="search"></i>
      </ng-template>
    </div>
    <div class="cui-mail-tabs">
      <nz-tabset nzTabPosition="left" [nzSelectedIndex]="activeCategoryIndex">
        <nz-tab [nzTitle]="categoryTabTemplate" *ngFor="let category of mailCategories">
          <ng-template #categoryTabTemplate>
            <div class="cui-mail-tab" (click)="changeMailData(category.key)">
              <div class="cui-mail-tab-content">
                <div class="mb-1">
                  <strong>
                    {{category.title}} <span *ngIf="category.mailCount > 0">({{category.mailCount}})</span>
                  </strong>
                  <div *ngIf="category.mailCount > 0">
                    <small class="cui-mail-tab-time">8:34PM</small>
                    <div class="cui-mail-tab-name">Barak Obama</div>
                    <div class="cui-mail-tab-text">
                      Hello! Where you are now? I want to talk. Hello! Where you are now? I want to talk
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </ng-template>
        </nz-tab>
      </nz-tabset>
    </div>
  </div>
  <div class="cui-mail-content">
    <div class="cui-mail-content-header">
      <div class="clearfix">
        <div class="pull-right mr-3">
          <button nz-button nzType="primary">Compose mail</button>
        </div>
        <nz-tabset>
          <nz-tab [nzTitle]="primaryTabTemplate">
            <ng-template #primaryTabTemplate>
              <i nz-icon type="home" theme="outline"></i>Primary
            </ng-template>
          </nz-tab>
          <nz-tab [nzTitle]="socialTabTemplate">
            <ng-template #socialTabTemplate>
              <i nz-icon type="message" theme="outline"></i>Social
            </ng-template>
          </nz-tab>
          <nz-tab [nzTitle]="promotionTabTemplate">
            <ng-template #promotionTabTemplate>
              <i nz-icon type="tags" theme="outline"></i>Promotion
            </ng-template>
          </nz-tab>
        </nz-tabset>
      </div>
    </div>
    <nz-table #mailTable [nzData]="mail" class="utils__scrollTable">
      <thead>
        <tr>
          <th></th>
          <th>From</th>
          <th>Message</th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <tr *ngFor="let data of mail">
          <td>
            <i [ngClass]="[data.favorites ? 'icmn-star-full text-warning' : 'icmn-star-full text-default']"></i>
          </td>
          <td>
            <a href="javascript: void(0);">{{data.from}}</a>
          </td>
          <td>
            {{data.message}}
          </td>
          <td>
            <i *ngIf="data.attachments" class="icmn-attachment text-default"></i>
          </td>
          <td>
            {{data.time}}
          </td>
        </tr>
      </tbody>
    </nz-table>
  </div>
</div>
