// cleanui-admin-template-vue/src/components/LayoutComponents/Topbar/LiveSearch/index.vue
<template>
  <div class="d-inline-block mr-4" @keydown.esc="closeSearch()">
    <a-input
      :class="$style.extInput"
      placeholder="Inpit search text..."
      style="width: 200px;"
      @focus="openSearch"
      ref="outerInput"
    >
      <a-icon slot="prefix" type="search" />
    </a-input>
    <div :class="[$style.livesearch, showSearch ? $style.livesearchVisible : '']">
      <button @click="closeSearch" :class="$style.close" type="button">
        <span class="utils__visibilityHidden">Закрыть</span>
        <i class="icmn-cross"></i>
      </button>
      <div class="container-fluid">
        <div :class="$style.wrapper">
          <div :class="$style.logoContainer">
            <img :class="$style.logo" src="resources/images/logo.png" />
          </div>
          <a-input :class="$style.searchInput" placeholder="Type to search..." ref="innerInput" />
          <ul :class="$style.options">
            <li :class="[$style.option, $style.optionCheckbox]">
              <a-checkbox>Search within page</a-checkbox>
            </li>
            <li :class="$style.option">Press enter to search</li>
          </ul>
          <div :class="$style.results">
            <div :class="$style.resultsTitle">
              <span>Pages Search Results</span>
            </div>
            <div class="row">
              <div class="col-lg-4">
                <div :class="$style.resultContent">
                  <div
                    :class="$style.resultThumb"
                    :style="{backgroundImage: 'url(\'resources/images/photos/1.jpeg\')'}"
                  >#1</div>
                  <div :class="$style.result">
                    <div :class="$style.resultText">Text from input field must be here</div>
                    <div :class="$style.resultSource">In some partition</div>
                  </div>
                </div>
                <div :class="$style.resultContent">
                  <div
                    :class="$style.resultThumb"
                    :style="{backgroundImage: 'url(\'resources/images/photos/2.jpeg\')'}"
                  >#2</div>
                  <div :class="$style.result">
                    <div :class="$style.resultText">Text from input field must be here</div>
                    <div :class="$style.resultSource">In some partition</div>
                  </div>
                </div>
                <div :class="$style.resultContent">
                  <div
                    :class="$style.resultThumb"
                    :style="{backgroundImage: 'url(\'resources/images/photos/3.jpeg\')'}"
                  >#3</div>
                  <div :class="$style.result">
                    <div :class="$style.resultText">Text from input field must be here</div>
                    <div :class="$style.resultSource">In some partition</div>
                  </div>
                </div>
              </div>
              <div class="col-lg-4">
                <div :class="$style.resultContent">
                  <div :class="$style.resultThumb">01</div>
                  <div :class="$style.result">
                    <div :class="$style.resultText">Text from input field must be here</div>
                    <div :class="$style.resultSource">In some partition</div>
                  </div>
                </div>
                <div :class="$style.resultContent">
                  <div :class="$style.resultThumb">02</div>
                  <div :class="$style.result">
                    <div :class="$style.resultText">Text from input field must be here</div>
                    <div :class="$style.resultSource">In some partition</div>
                  </div>
                </div>
                <div :class="$style.resultContent">
                  <div :class="$style.resultThumb">03</div>
                  <div :class="$style.result">
                    <div :class="$style.resultText">Text from input field must be here</div>
                    <div :class="$style.resultSource">In some partition</div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  data: function () {
    return {
      showSearch: false,
    }
  },
  methods: {
    openSearch() {
      this.showSearch = true
      setTimeout(() => {
        this.$refs.innerInput.focus()
      }, 100)
    },
    closeSearch() {
      this.showSearch = false
    },
  },
}
</script>

<style lang="scss" module>
@import "./style.module.scss";
</style>

// cleanui-admin-template-react-umi-seed/src/components/LayoutComponents/TopBar/LiveSearch/index.js
import React from 'react'
import { Input, Icon, Checkbox } from 'antd'
import { formatMessage } from 'umi/locale'
import styles from './style.module.scss'

class LiveSearch extends React.Component {
  state = {
    showSearch: false,
    searchText: '',
  }

  componentWillMount() {
    document.addEventListener('keydown', this.handleKeyDown, false)
  }

  showLiveSearch = () => {
    setTimeout(() => {
      this.searchInput.focus()
    }, 100)
    this.setState({
      showSearch: true,
    })
  }

  changeSearchText = e => {
    this.setState({
      searchText: e.target.value,
    })
  }

  hideLiveSearch = () => {
    this.searchInput.blur()
    this.setState({
      showSearch: false,
      searchText: '',
    })
  }

  handleKeyDown = event => {
    const { showSearch } = this.state
    if (showSearch) {
      const key = event.keyCode.toString()
      if (key === '27') {
        this.hideLiveSearch()
      }
    }
  }

  handleNode = node => {
    this.searchInput = node
  }

  render() {
    const { showSearch, searchText } = this.state

    return (
      <div className="d-inline-block mr-4">
        <Input
          className={styles.extInput}
          placeholder={formatMessage({ id: 'topBar.typeToSearch' })}
          prefix={<Icon type="search" style={{ color: 'rgba(0,0,0,.25)' }} />}
          style={{ width: 200 }}
          onFocus={this.showLiveSearch}
        />
        <div
          className={`${
            showSearch ? `${styles.livesearch} ${styles.livesearchVisible}` : styles.livesearch
          }`}
          id="livesearch"
        >
          <button className={styles.close} type="button" onClick={this.hideLiveSearch}>
            <span className="utils__visibilityHidden">Закрыть</span>
            <i className="icmn-cross" />
          </button>
          <div className="container-fluid">
            <div className={styles.wrapper}>
              <div className={styles.logoContainer}>
                <img className={styles.logo} src="resources/images/logo.png" alt="" />
              </div>
              <input
                type="search"
                className={styles.searchInput}
                value={searchText}
                onChange={this.changeSearchText}
                id="livesearchInput"
                placeholder="Type to search..."
                ref={this.handleNode}
              />
              <ul className={styles.options}>
                <li className={`${styles.option} ${styles.optionCheckbox}`}>
                  <Checkbox>Search within page</Checkbox>
                </li>
                <li className={styles.option}>Press enter to search</li>
              </ul>
              <div className={styles.results}>
                <div className={styles.resultsTitle}>
                  <span>Pages Search Results</span>
                </div>
                <div className="row">
                  <div className="col-lg-4">
                    <div className={styles.resultContent}>
                      <div
                        className={styles.resultThumb}
                        style={{ backgroundImage: 'url(resources/images/photos/1.jpeg)' }}
                      >
                        #1
                      </div>
                      <div className={styles.result}>
                        <div className={styles.resultText}>Text from input field must be here</div>
                        <div className={styles.resultSource}>In some partition</div>
                      </div>
                    </div>
                    <div className={styles.resultContent}>
                      <div
                        className={styles.resultThumb}
                        style={{ backgroundImage: 'url(resources/images/photos/2.jpeg)' }}
                      >
                        KF
                      </div>
                      <div className={styles.result}>
                        <div className={styles.resultText}>Text from input field must be here</div>
                        <div className={styles.resultSource}>In some partition</div>
                      </div>
                    </div>
                    <div className={styles.resultContent}>
                      <div
                        className={styles.resultThumb}
                        style={{ backgroundImage: 'url(resources/images/photos/3.jpeg)' }}
                      >
                        GF
                      </div>
                      <div className={styles.result}>
                        <div className={styles.resultText}>Text from input field must be here</div>
                        <div className={styles.resultSource}>In some partition</div>
                      </div>
                    </div>
                  </div>
                  <div className="col-lg-4">
                    <div className={styles.resultContent}>
                      <div className={styles.resultThumb}>01</div>
                      <div className={styles.result}>
                        <div className={styles.resultText}>Text from input field must be here</div>
                        <div className={styles.resultSource}>In some partition</div>
                      </div>
                    </div>
                    <div className={styles.resultContent}>
                      <div className={styles.resultThumb}>02</div>
                      <div className={styles.result}>
                        <div className={styles.resultText}>Text from input field must be here</div>
                        <div className={styles.resultSource}>In some partition</div>
                      </div>
                    </div>
                    <div className={styles.resultContent}>
                      <div className={styles.resultThumb}>03</div>
                      <div className={styles.result}>
                        <div className={styles.resultText}>Text from input field must be here</div>
                        <div className={styles.resultSource}>In some partition</div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    )
  }
}

export default LiveSearch
