// cleanui-admin-template-vue/src/views/apps/profile/index.vue
<template>
  <div :class="$style.profile">
    <div class="row">
      <div class="col-xl-4">
        <div
          class="card"
          :class="$style.header"
          :style="{ backgroundImage: 'url(' + background + ')'}"
        >
          <div class="card-body text-center">
            <cui-avatar :src="photo" size="110" bordered="true" :borderColor="white"/>
            <br>
            <br>
            <a-button-group>
              <a-button style="width: 150px;">Follow</a-button>
              <a-button style="width: 150px;">Add to Friend</a-button>
            </a-button-group>
            <br>
            <p class="text-white mt-2">Last activity: {{lastActivity}}</p>
            <p class="text-white mt-2">
              <cui-donut :name="status" :type="status === 'Online' ? 'success' : 'danger'"/>
            </p>
          </div>
        </div>
        <div class="card">
          <div class="card-body">
            <h5 class="mb-3 text-black">
              <strong>Actions</strong>
            </h5>
            <div :class="$style.actions">
              <a-button style="display: block; width: 100%;">Send Message</a-button>
              <a-button style="display: block; width: 100%;">Send File</a-button>
              <a-button style="display: block; width: 100%;">Access History</a-button>
              <a-button style="display: block; width: 100%;">Rename User</a-button>
              <a-button style="display: block; width: 100%;">Ban User</a-button>
            </div>
          </div>
        </div>
        <div class="card">
          <div class="card-body">
            <h5 class="mb-3 text-black">
              <strong>Skills</strong>
            </h5>
            <div v-for="(skill, index) in skills" :key="index">
              <div class="mb-1">{{skill.name}}</div>
              <a-progress :percent="skill.value" :showInfo="false"/>
            </div>
          </div>
        </div>
        <div class="card">
          <div class="card-body">
            <h5 class="mb-3 text-black">
              <strong>Information</strong>
            </h5>
            <dl class="row">
              <dt class="col-xl-3">Courses End:</dt>
              <dd class="col-xl-9">{{coursesEnd}}</dd>
              <dt class="col-xl-3">Address:</dt>
              <dd class="col-xl-9">{{adress}}</dd>
              <dt class="col-xl-3">Skills:</dt>
              <dd class="col-xl-9">
                <span
                  class="badge badge-default mr-1"
                  :key="index"
                  v-for="(skill, index) in profSkills"
                >{{skill}}</span>
              </dd>
              <dt class="col-xl-3">Last companies:</dt>
              <dd class="col-xl-9">{{lastCompanies}}</dd>
              <dt class="col-xl-3">Personal Information:</dt>
              <dd class="col-xl-9">{{personal}}</dd>
            </dl>
          </div>
        </div>
        <div class="card">
          <div class="card-body">
            <h5 class="mb-3 text-black">
              <strong>Calendar</strong>
            </h5>
            <a-calendar :fullscreen="false"/>
          </div>
        </div>
      </div>
      <div class="col-xl-8">
        <div :class="$style.socialInfo" class="card card-body mb-4">
          <div>
            <h2>
              <span class="text-black mr-2">
                <strong>{{name}}</strong>
              </span>
              <small class="text-muted">{{nickname}}</small>
            </h2>
            <p class="mb-1">{{post}}</p>
          </div>
          <div :class="$style.socialCounts">
            <div class="text-center mr-3">
              <h2>{{followersCount}}</h2>
              <p class="mb-0">Followers</p>
            </div>
            <div class="text-center mr-3">
              <h2>{{postsCount}}</h2>
              <p class="mb-0">Followers</p>
            </div>
          </div>
        </div>
        <div class="card">
          <div class="card-body">
            <a-tabs defaultActiveKey="1">
              <a-tab-pane key="1">
                <span slot="tab">
                  <span>
                    <i class="icmn-menu"/> Wall
                  </span>
                </span>
                <div class="py-3">
                  <a-textarea placeholder="Basic usage" :rows="4"/>
                  <div class="mt-3">
                    <a-button class="mr-2" type="primary" style="width: 200px">
                      <i class="fa fa-send mr-2"/>
                      Create Post
                    </a-button>
                    <a-upload
                      name="file"
                      :multiple="true"
                      action="//jsonplaceholder.typicode.com/posts/"
                      :headers="headers"
                      @change="handleChange"
                    >
                      <a-button>
                        <a-icon type="upload"/>Click to Upload
                      </a-button>
                    </a-upload>
                  </div>
                </div>
                <div v-for="(item, index) in posts" :key="index">
                  <div :class="$style.wallItem" class="clearfix">
                    <div :class="$style.wallAvatar">
                      <cui-avatar size="50" :src="item.avatar" :bordered="false"/>
                    </div>
                    <div :class="$style.wallContent">
                      <div class="mb-3">
                        <div class="pull-right">
                          <a-dropdown>
                            <a class="ant-dropdown-link" href="javascript: void(0);">Actions
                              <a-icon type="down"/>
                            </a>
                            <a-menu slot="overlay">
                              <a-menu-item>
                                <a href="javascript:void(0)">
                                  <a-icon type="edit"/>Edit Post
                                </a>
                              </a-menu-item>
                              <a-menu-item>
                                <a href="javascript:void(0)">
                                  <a-icon type="delete"/>Delete Post
                                </a>
                              </a-menu-item>
                              <a-menu-item>
                                <a href="javascript:void(0)">
                                  <a-icon type="frown-o"/>Mark as a Spam
                                </a>
                              </a-menu-item>
                            </a-menu>
                          </a-dropdown>
                        </div>
                        <strong>{{item.name}}</strong> posted:
                        <br>
                        <small class="text-muted">{{item.date}}</small>
                      </div>
                      <div class="mb-3" v-html="item.content"></div>
                      <a href="javascript: void(0);" class="mr-3">
                        <i class="icmn-heart mr-2"/>
                        <span v-if="item.likesCount > 0">{{item.likesCount}} Likes</span>
                        <span v-if="item.likesCount === 0">{{item.likesCount}} Like</span>
                      </a>
                      <a href="javascript: void(0);" class="mr-3">
                        <i class="icmn-bubble mr-2"/>
                        <span v-if="item.commentsCount > 0">{{item.commentsCount}} Comments</span>
                        <span v-if="item.commentsCount === 0">{{item.commentsCount}} Comment</span>
                      </a>
                    </div>
                  </div>
                  <div :class="[$style.wallContent, $style.wallInnerContent]">
                    <div :class="$style.wallComments">
                      <div
                        :class="$style.wallItem"
                        class="clearfix"
                        v-for="(postComment, index) in item.comments"
                        :key="index"
                      >
                        <div :class="$style.wallAvatar">
                          <cui-avatar size="50" :src="postComment.avatar" :bordered="false"/>
                        </div>
                        <div :class="$style.wallContent">
                          <div class="clearfix">
                            <div class="pull-right">
                              <a-dropdown>
                                <a class="ant-dropdown-link" href="javascript: void(0);">Actions
                                  <a-icon type="down"/>
                                </a>
                                <a-menu slot="overlay">
                                  <a-menu-item>
                                    <a href="javascript:void(0)">
                                      <a-icon type="edit"/>Edit Post
                                    </a>
                                  </a-menu-item>
                                  <a-menu-item>
                                    <a href="javascript:void(0)">
                                      <a-icon type="delete"/>Delete Post
                                    </a>
                                  </a-menu-item>
                                  <a-menu-item>
                                    <a href="javascript:void(0)">
                                      <a-icon type="frown-o"/>Mark as a Spam
                                    </a>
                                  </a-menu-item>
                                </a-menu>
                              </a-dropdown>
                            </div>
                            <strong>{{postComment.name}}</strong> posted:
                            <br>
                            <small class="text-muted">{{postComment.date}}</small>
                          </div>
                          <div class="mb-3" v-html="postComment.content"></div>
                          <a href="javascript: void(0);" class="mr-3">
                            <i class="icmn-heart mr-2"/>
                            <span v-if="postComment.likesCount > 0">{{postComment.likesCount}} Likes</span>
                            <span
                              v-if="postComment.likesCount === 0"
                            >{{postComment.likesCount}} Like</span>
                          </a>
                          <a href="javascript: void(0);" class="mr-3">
                            <i class="icmn-bubble mr-2"/>
                            <span
                              v-if="postComment.commentsCount > 0"
                            >{{postComment.commentsCount}} Comments</span>
                            <span
                              v-if="postComment.commentsCount === 0"
                            >{{postComment.commentsCount}} Comment</span>
                          </a>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </a-tab-pane>
              <a-tab-pane key="2">
                <span slot="tab">
                  <span>
                    <i class="icmn-bubbles"/> Messages
                  </span>
                </span>
                <cui-chat/>
              </a-tab-pane>
              <a-tab-pane key="3">
                <span slot="tab">
                  <i class="icmn-cog"/> Settings
                </span>
                <a-form :form="form">
                  <h5 class="text-black mt-2 mb-3">
                    <strong>Personal Information</strong>
                  </h5>
                  <div class="row">
                    <div class="col-lg-6">
                      <a-form-item label="Username">
                        <a-input placeholder="Username" v-decorator="['username']"/>
                      </a-form-item>
                    </div>
                    <div class="col-lg-6">
                      <a-form-item label="Email">
                        <a-input placeholder="Email" v-decorator="['discount']"/>
                      </a-form-item>
                    </div>
                  </div>
                  <h5 class="text-black mt-2 mb-3">
                    <strong>New Password</strong>
                  </h5>
                  <div class="row">
                    <div class="col-lg-6">
                      <a-form-item label="Password">
                        <a-input placeholder="Password" v-decorator="['password']"/>
                      </a-form-item>
                    </div>
                    <div class="col-lg-6">
                      <a-form-item label="Confirm Password">
                        <a-input placeholder="Confirm Password" v-decorator="['confirmPassword']"/>
                      </a-form-item>
                    </div>
                  </div>
                  <div class="row">
                    <div class="col-lg-6">
                      <h5 class="text-black mt-2 mb-3">
                        <strong>Profile Avatar</strong>
                      </h5>
                      <a-form-item>
                        <a-upload
                          name="file"
                          :multiple="true"
                          action="//jsonplaceholder.typicode.com/posts/"
                          :headers="headers"
                          @change="handleChange"
                        >
                          <a-button>
                            <a-icon type="upload"/>Click to Upload
                          </a-button>
                        </a-upload>
                      </a-form-item>
                    </div>
                    <div class="col-lg-6">
                      <h5 class="text-black mt-2 mb-3">
                        <strong>Profile Background</strong>
                      </h5>
                      <a-form-item>
                        <a-upload
                          name="file"
                          :multiple="true"
                          action="//jsonplaceholder.typicode.com/posts/"
                          :headers="headers"
                          @change="handleChange"
                        >
                          <a-button>
                            <a-icon type="upload"/>Click to Upload
                          </a-button>
                        </a-upload>
                      </a-form-item>
                    </div>
                  </div>
                  <div class="form-actions mt-0">
                    <a-button
                      style="width: 150px;"
                      type="primary"
                      htmlType="submit"
                      class="mr-3"
                    >Submit</a-button>
                    <a-button htmlType="submit">Cancel</a-button>
                  </div>
                </a-form>
              </a-tab-pane>
            </a-tabs>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import {
  name,
  nickname,
  photo,
  background,
  post,
  postsCount,
  followersCount,
  lastActivity,
  status,
  skills,
  coursesEnd,
  adress,
  profSkills,
  lastCompanies,
  personal,
  posts,
} from './data.json'
import CuiAvatar from '@/components/CleanUIComponents/Avatar'
import CuiDonut from '@/components/CleanUIComponents/Donut'
import CuiChat from '@/components/CleanUIComponents/Chat'

export default {
  components: {
    CuiAvatar,
    CuiDonut,
    CuiChat,
  },
  data: function () {
    return {
      name,
      nickname,
      photo,
      background,
      post,
      postsCount,
      followersCount,
      lastActivity,
      status,
      skills,
      coursesEnd,
      adress,
      profSkills,
      lastCompanies,
      personal,
      posts,
      form: this.$form.createForm(this),
    }
  },
  methods: {
    handleChange(info) {
      if (info.file.status !== 'uploading') {
        console.log(info.file, info.fileList)
      }
      if (info.file.status === 'done') {
        this.$message.success(`${info.file.name} file uploaded successfully`)
      } else if (info.file.status === 'error') {
        this.$message.error(`${info.file.name} file upload failed.`)
      }
    },
  },
}
</script>

<style lang="scss" module>
@import "./style.module.scss";
</style>

// cleanui-admin-template-angular/src/app/pages/apps/profile/profile.component.ts
import { Component } from '@angular/core'
declare var require: any
const data: any = require('./data.json')

@Component({
  selector: 'app-apps-profile',
  templateUrl: './profile.component.html',
  styleUrls: ['./profile.component.scss'],
})
export class AppsProfileComponent {
  name = data.name
  nickname = data.nickname
  photo = data.photo
  background = data.background
  post = data.post
  postsCount = data.postsCount
  followersCount = data.followersCount
  lastActivity = data.lastActivity
  status = data.status
  skills = data.skills
  coursesEnd = data.coursesEnd
  adress = data.adress
  profSkills = data.profSkills
  lastCompanies = data.lastCompanies
  personal = data.personal
  posts = data.posts

  formLayout = 'vertical'
}

<div class="cui-profile">
  <div class="row">
    <div class="col-xl-4">
      <div class="card cui-profile-header" [ngStyle]="{'background-image': 'url(' + background + ')'}">
        <div class="card-body text-center">
          <cui-avatar [src]="photo" [size]="110" [bordered]="true" borderColor="#fff"></cui-avatar>
          <br>
          <br>
          <nz-button-group>
            <button nz-button style="width: 150px;">Follow</button>
            <button nz-button style="width: 150px;">Add to Friend</button>
          </nz-button-group>
          <br>
          <p class="text-white mt-2">Last activity {{lastActivity}}</p>
          <p class="text-white mt-2">
            <cui-donut type="danger" [name]="status"></cui-donut>
          </p>
        </div>
      </div>
      <div class="card">
        <div class="card-body">
          <h5 class="mb-3 text-black">
            <strong>Actions</strong>
          </h5>
          <div class="cui-profile-actions">
            <button nz-button style="width: 100%; display: block">Send Message</button>
            <button nz-button style="width: 100%; display: block">Send File</button>
            <button nz-button style="width: 100%; display: block">Access History</button>
            <button nz-button style="width: 100%; display: block">Rename User</button>
            <button nz-button style="width: 100%; display: block">Ban User</button>
          </div>
        </div>
      </div>
      <div class="card">
        <div class="card-body">
          <h5 class="mb-3 text-black">
            <strong>Skills</strong>
          </h5>
          <div *ngFor="let skill of skills">
            <div class="mb-1">{{skill.name}}</div>
            <nz-progress [nzPercent]="skill.value" [nzShowInfo]="false"></nz-progress>
          </div>
        </div>
      </div>
      <div class="card">
        <div class="card-body">
          <h5 class="mb-3 text-black">
            <strong>Information</strong>
          </h5>
          <dl class="row">
            <dt class="col-xl-3">Courses End:</dt>
            <dd class="col-xl-9">{{coursesEnd}}</dd>
            <dt class="col-xl-3">Address:</dt>
            <dd class="col-xl-9">{{adress}}</dd>
            <dt class="col-xl-3">Skills:</dt>
            <dd class="col-xl-9">
              <span class="badge badge-default mr-1" *ngFor="let skill of profSkills">
                {{skill}}
              </span>
            </dd>
            <dt class="col-xl-3">Last companies:</dt>
            <dd class="col-xl-9">{{lastCompanies}}</dd>
            <dt class="col-xl-3">Personal Information:</dt>
            <dd class="col-xl-9">{{personal}}</dd>
          </dl>
        </div>
      </div>
      <div class="card">
        <div class="card-body">
          <h5 class="mb-3 text-black">
            <strong>Calendar</strong>
          </h5>
          <nz-calendar nzCard></nz-calendar>
        </div>
      </div>
    </div>
    <div class="col-xl-8">
      <div class="card card-body mb4">
        <div>
          <h2>
            <span class="text-black mr-2">
              <strong>{{name}}</strong>
            </span>
            <small class="text-muted">{{nickname}}</small>
          </h2>
          <p class="mb-1">{{post}}</p>
        </div>
        <div class="cui-profile-social-counts">
          <div class="text-center mr-3">
            <h2>{{followersCount}}</h2>
            <p class="mb-0">Followers</p>
          </div>
          <div class="text-center">
            <h2>{{postsCount}}</h2>
            <p class="mb-0">Posts</p>
          </div>
        </div>
      </div>
      <div class="card">
        <div class="card-body">
          <nz-tabset>
            <nz-tab [nzTitle]="wallTabTemplate">
              <ng-template #wallTabTemplate>
                <i class="icmn-menu mr-1"></i> Wall
              </ng-template>
              <div class="py-3">
                <textarea rows="3" nz-input></textarea>
                <div class="mt-3">
                  <button nz-button nzType="primary" style="width: 200px;" class="mr-2">
                    <i class="fa fa-send mr-2"></i> Create Post
                  </button>
                  <nz-upload
                    nzAction="https://jsonplaceholder.typicode.com/posts/">
                    <button nz-button>
                      <i nz-icon type="upload"></i><span>Attach File</span>
                    </button>
                  </nz-upload>
                </div>
              </div>
              <hr>
              <div *ngFor="let item of posts">
                <div class="cui-profile-wall-item clearfix">
                  <div class="cui-profile-wall-avatar">
                    <cui-avatar [src]="item.avatar" [bordered]="false" [size]="50"></cui-avatar>
                  </div>
                  <div class="cui-profile-wall-content">
                    <div class="mb-3">
                      <div class="pull-right">
                        <nz-dropdown>
                          <a nz-dropdown>
                            Actions <i nz-icon type="down"></i>
                          </a>
                          <ul nz-menu nzSelectable>
                            <li nz-menu-item>
                              <i nz-icon [type]="'edit'"></i> Edit Post
                            </li>
                            <li nz-menu-item>
                              <i nz-icon [type]="'delete'"></i> Delete Post
                            </li>
                            <li nz-menu-item>
                              <i nz-icon [type]="'frown-o'"></i> Mark as a Spam
                            </li>
                          </ul>
                        </nz-dropdown>
                      </div>
                      <strong>{{item.name}}</strong> posted:
                      <br>
                      <small class="text-muted">{{item.date}}</small>
                    </div>
                    <div [innerHtml]="item.content" class="mb-3"></div>
                    <div class="mr-3">
                      <a href="javascript: void(0);" class="mr-3">
                        <i class="icmn-heart mr-2"></i> <span>{{item.likesCount}} Likes</span>
                      </a>
                      <a href="javascript: void(0);">
                        <i class="icmn-bubble mr-2"></i> <span>{{item.commentsCount}} Comments</span>
                      </a>
                    </div>
                  </div>
                </div>
                <div class="cui-profile-wall-content cui-profile-wall-inner-content">
                  <div *ngIf="item.comments.length > 0" class="cui-profile-wall-comments">
                    <div class="cui-profile-wall-item clearfix" *ngFor="let postComment of item.comments">
                      <div class="cui-profile-wall-avatar">
                        <cui-avatar [size]="50" [src]="postComment.avatar" [bordered]="false"></cui-avatar>
                      </div>
                      <div class="cui-profile-wall-content">
                        <div class="mb-3">
                          <div class="pull-right">
                            <nz-dropdown>
                              <a nz-dropdown>
                                Actions <i nz-icon type="down"></i>
                              </a>
                              <ul nz-menu nzSelectable>
                                <li nz-menu-item>
                                  <i nz-icon [type]="'edit'"></i> Edit Post
                                </li>
                                <li nz-menu-item>
                                  <i nz-icon [type]="'delete'"></i> Delete Post
                                </li>
                                <li nz-menu-item>
                                  <i nz-icon [type]="'frown-o'"></i> Mark as a Spam
                                </li>
                              </ul>
                            </nz-dropdown>
                          </div>
                          <strong>{{postComment.name}}</strong> posted:
                          <br>
                          <small class="text-muted">{{postComment.date}}</small>
                        </div>
                        <div [innerHtml]="postComment.content"></div>
                        <div>
                          <a href="javascript: void(0);" class="mr-3">
                            <i class="icmn-heart mr-2"></i> <span>{{item.likesCount}} Likes</span>
                          </a>
                          <a href="javascript: void(0);">
                            <i class="icmn-bubble mr-2"></i> <span>{{item.commentsCount}} Comments</span>
                          </a>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </nz-tab>
            <nz-tab [nzTitle]="chatTabTemplate">
              <ng-template #chatTabTemplate>
                <i class="icmn-bubbles mr-1"></i> Messages
              </ng-template>
              <cui-chat></cui-chat>
            </nz-tab>
            <nz-tab [nzTitle]="settingsTabTemplate">
              <ng-template #settingsTabTemplate>
                <i class="icmn-cog mr-1"></i> Settings
              </ng-template>
              <form nz-form [nzLayout]="formLayout">
                <h5 class="text-black mt-4">
                  <strong>Personal Information</strong>
                </h5>
                <div class="row">
                  <div class="col-lg-6">
                    <nz-form-item>
                      <nz-form-label nzFor="userName">Username:</nz-form-label>
                      <nz-form-control>
                        <input nz-input placeholder="Username" id="userName">
                      </nz-form-control>
                    </nz-form-item >
                  </div>
                  <div class="col-lg-6">
                    <nz-form-item>
                      <nz-form-label nzFor="email">Email:</nz-form-label>
                      <nz-form-control>
                        <input nz-input placeholder="Email" id="email">
                      </nz-form-control>
                    </nz-form-item >
                  </div>
                </div>
                <h5 class="text-black mt-4">
                  <strong>New Password</strong>
                </h5>
                <div class="row">
                  <div class="col-lg-6">
                    <nz-form-item>
                      <nz-form-label nzFor="password">Password:</nz-form-label>
                      <nz-form-control>
                        <input nz-input placeholder="Password" id="password">
                      </nz-form-control>
                    </nz-form-item>
                  </div>
                  <div class="col-lg-6">
                    <nz-form-item>
                      <nz-form-label nzFor="confPassword">Confirm Password:</nz-form-label>
                      <nz-form-control>
                        <input nz-input placeholder="Confirm password" id="confPassword">
                      </nz-form-control>
                    </nz-form-item>
                  </div>
                </div>
                <div class="row">
                  <div class="col-lg-6">
                    <h5 class="text-black mt-4 mb-3">
                      <strong>Profile Avatar</strong>
                    </h5>
                    <nz-upload
                      nzAction="https://jsonplaceholder.typicode.com/posts/">
                      <button nz-button>
                        <i nz-icon type="upload"></i><span>Click to Upload</span>
                      </button>
                    </nz-upload>
                  </div>
                  <div class="col-lg-6">
                    <h5 class="text-black mt-4 mb-3">
                      <strong>Profile Background</strong>
                    </h5>
                    <nz-upload
                      nzAction="https://jsonplaceholder.typicode.com/posts/">
                      <button nz-button>
                        <i nz-icon type="upload"></i><span>Click to Upload</span>
                      </button>
                    </nz-upload>
                  </div>
                </div>
                <div class="form-actions">
                  <button nz-button style="width: 150px;" [nzType]="'primary'" class="mr-3">Submit</button>
                  <button nz-button>Cancel</button>
                </div>
              </form>
            </nz-tab>
          </nz-tabset>
        </div>
      </div>
    </div>
  </div>
</div>
