// cleanui-admin-template-vue/src/components/LayoutComponents/Topbar/ProjectManagement/index.vue
<template>
  <a-dropdown :trigger="['click']" placement="bottomLeft">
    <div :class="$style.dropdown">
      <i class="icmn-database" :class="$style.icon"></i>
      <span class="d-none d-xl-inline">
        <strong>Project Management</strong>
      </span>
    </div>
    <a-menu slot="overlay">
      <a-menu-item-group title="Active">
        <a-menu-item>
          <a href="javascript: void(0);">Project Management</a>
        </a-menu-item>
        <a-menu-item>
          <a href="javascript: void(0);">User Interface Development</a>
        </a-menu-item>
        <a-menu-item>
          <a href="javascript: void(0);">Documentation</a>
        </a-menu-item>
      </a-menu-item-group>
      <a-menu-item-group title="Inactive">
        <a-menu-item>
          <a href="javascript: void(0);">Marketing</a>
        </a-menu-item>
      </a-menu-item-group>
      <a-menu-divider/>
      <a-menu-item>
        <a href="javascript: void(0);">
          <i class="icmn-cog" :class="$style.menuIcon"/>
          Settings
        </a>
      </a-menu-item>
    </a-menu>
  </a-dropdown>
</template>

<style lang="scss" module>
@import "./style.module.scss";
</style>

// cleanui-admin-template-react-umi-seed/src/components/LayoutComponents/TopBar/ProjectManagement/index.js
import React from 'react'
import { Menu, Dropdown } from 'antd'
import { formatMessage } from 'umi/locale'
import Link from 'umi/link'
import styles from './style.module.scss'

class ProjectManagement extends React.Component {
  render() {
    const menu = (
      <Menu selectable={false}>
        <span className={styles.title}>
          <strong>Active</strong>
        </span>
        <Menu.Item>
          <Link to="/">Project Management</Link>
        </Menu.Item>
        <Menu.Item>
          <Link to="/">User Interface Development</Link>
        </Menu.Item>
        <Menu.Item>
          <Link to="/">Documentation</Link>
        </Menu.Item>
        <span className={styles.title}>
          <strong>Inactive</strong>
        </span>
        <Menu.Item>
          <Link to="/">Marketing</Link>
        </Menu.Item>
        <Menu.Divider />
        <Menu.Item>
          <Link to="/">
            <i className={`${styles.menuIcon} icmn-cog`} /> Settings
          </Link>
        </Menu.Item>
      </Menu>
    )
    return (
      <Dropdown overlay={menu} trigger={['click']} placement="bottomLeft">
        <div className={styles.dropdown}>
          <i className={`${styles.icon} icmn-database`} />
          <span className="d-none d-xl-inline">
            <strong>{formatMessage({ id: 'topBar.projectManagement' })}</strong>
          </span>
        </div>
      </Dropdown>
    )
  }
}

export default ProjectManagement
