// cleanui-admin-template-angular/src/app/pages/blog/post/post.component.ts
import { Component } from '@angular/core'
declare var require: any
const data: any = require('./data.json')

@Component({
  selector: 'app-blog-post',
  templateUrl: './post.component.html',
  styleUrls: ['./post.component.scss'],
})
export class BlogPostComponent {
  articleData = data.articleData
  articlesCategories = data.articlesCategories
  latesArticlesData = data.latesArticlesData
  comments = data.comments
}

<section class="card">
  <div class="card-header">
    <div class="utils__title">
      <strong>Blog Post</strong>
    </div>
  </div>
  <div class="card-body">
    <div class="blogFeed">
      <div class="row">
        <div class="col-lg-8">
          <article class="article">
            <div class="information">
              <div class="title">
                <h1>
                  <a href="javascript: void(0);">{{articleData.name}}</a>
                </h1>
              </div>
              <ul class="meta">
                <li class="metaInf">
                  <span class="articleAuthor">
                    Post By <a href="javascript: void(0);">{{articleData.author}}</a>
                  </span>
                </li>
                <li class="metaInf">
                  <span class="articleDate">On {{articleData.date}}</span>
                </li>
              </ul>
            </div>
            <div class="content" [innerHtml]="articleData.content"></div>
            <footer class="footer">
              <div class="row">
                <div class="col-8">
                  <div class="hashtags">
                    <a href="javascript: void(0);" *ngFor="let tag of articleData.tags">
                      {{tag}}
                    </a>
                  </div>
                </div>
                <div class="col-4">
                  <ul class="share">
                    <li class="shareItem">
                      <a href="javascript: void(0);">
                        <i class="fa fa-facebook"></i>
                      </a>
                    </li>
                    <li class="shareItem">
                      <a href="javascript: void(0);">
                        <i class="fa fa-twitter"></i>
                      </a>
                    </li>
                    <li class="shareItem">
                      <a href="javascript: void(0);">
                        <i class="fa fa-pinterest-p"></i>
                      </a>
                    </li>
                  </ul>
                </div>
              </div>
            </footer>
          </article>
          <div class="authorCard clearfix">
            <div class="authorPhoto">
              <cui-avatar [src]="articleData.authorAvatar" [size]="110"></cui-avatar>
            </div>
            <div class="authorInf">
              <span class="authorName">{{articleData.author}}</span>
              <p class="authorWords">&ldquo;{{articleData.authorStatus}}&rdquo;</p>
              <div class="blog-feed__author-profile">
                <a
                  href="javascript: void(0);"
                  class="blog-feed__author-profile-btn btn btn-sm btn-primary"
                >
                  View Profile
                </a>
              </div>
            </div>
          </div>
          <div class="mb-4">
            <div class="commentsTitle">Leave a comment</div>
            <div class="addCommentForm">
              <form nz-form class="login-form">
                <nz-form-item>
                  <nz-form-control>
                    <nz-input-group [nzPrefix]="prefixUser">
                      <input formControlName="userPassword" nz-input placeholder="Your name">
                    </nz-input-group>
                  </nz-form-control>
                </nz-form-item>
                <nz-form-item>
                  <nz-form-control>
                    <nz-input-group [nzPrefix]="prefixMail">
                      <input formControlName="userPassword" nz-input placeholder="Your email">
                    </nz-input-group>
                  </nz-form-control>
                </nz-form-item>
                <nz-form-item>
                  <nz-form-control>
                    <nz-input-group>
                      <textarea rows="3" nz-input placeholder="Your message"></textarea>
                    </nz-input-group>
                  </nz-form-control>
                </nz-form-item>
                <nz-form-item>
                  <button nz-button nzType="primary" class="width-200 mr-4">
                    <i class="fa fa-send mr-2"></i>
                    Send
                  </button>
                  <nz-upload
                    nzAction="https://jsonplaceholder.typicode.com/posts/">
                    <button nz-button>
                      <i nz-icon type="upload"></i><span>Attach File</span>
                    </button>
                  </nz-upload>
                </nz-form-item>
                <ng-template #prefixUser><i nz-icon type="user"></i></ng-template>
                <ng-template #prefixMail><i nz-icon type="mail"></i></ng-template>
              </form>
            </div>
          </div>
          <div class="mb-4">
            <div class="commentsTitle">Comments</div>
            <div class="mt-3">
              <div *ngIf="comments.length > 0">
                <div *ngFor="let postComment of comments" class="clearfix commentItem" [ngClass]="[postComment.subComments ? 'pb-0' : '']">
                  <div class="commentAvatar">
                    <cui-avatar [src]="postComment.avatar" [size]="50" [bordered]="false"></cui-avatar>
                  </div>
                  <div class="commentContent">
                    <div class="clearfix">
                      <div class="pull-left">
                        <strong>{{postComment.name}}</strong> posted:
                        <br/>
                        <small class="text-muted">{{postComment.date}}</small>
                      </div>
                      <div class="pull-right">
                        <nz-dropdown>
                          <a nz-dropdown>
                            Actions <i nz-icon type="down"></i>
                          </a>
                          <ul nz-menu nzSelectable>
                            <li nz-menu-item>
                              <a><i nz-icon [type]="'edit'"></i> Edit Comment</a>
                            </li>
                            <li nz-menu-item>
                              <a><i nz-icon [type]="'delete'"></i> Delete Comment</a>
                            </li>
                            <li nz-menu-item>
                              <a><i nz-icon [type]="'exclamation-circle'"></i> Mark as a Spam</a>
                            </li>
                          </ul>
                        </nz-dropdown>
                      </div>
                    </div>
                    <div [innerHTML]="postComment.content"></div>
                    <div>
                      <a href="javascript: void(0);" class="mr-3">
                        <i class="icmn-heart mr-2"></i>
                        <span>{{postComment.likesCount}} Likes</span>
                      </a>
                      <a href="javascript: void(0);" class="mr-3">
                        <i class="icmn-bubble mr-2"></i>
                        <span>{{postComment.commentsCount}} Comments</span>
                      </a>
                      <a href="javascript: void(0);">
                        <i class="icmn-reply mr-2"></i>
                        <span>Reply</span>
                      </a>
                    </div>
                    <div *ngIf="postComment.subComments" class="subcommentsContent">
                      <div *ngFor="let subComment of postComment.subComments" class="commentItem clearfix">
                        <div class="commentAvatar">
                          <cui-avatar [size]="50" [src]="subComment.avatar" [bordered]="false"></cui-avatar>
                        </div>
                        <div class="commentContent">
                          <div class="clearfix">
                            <div class="pull-left">
                              <strong>{{subComment.name}}</strong> posted:
                              <br/>
                              <small class="text-muted">
                                {{subComment.date}}
                              </small>
                            </div>
                            <div class="pull-right">
                              <nz-dropdown>
                                <a nz-dropdown>
                                  Actions <i nz-icon type="down"></i>
                                </a>
                                <ul nz-menu nzSelectable>
                                  <li nz-menu-item>
                                    <a><i nz-icon [type]="'edit'"></i> Edit Comment</a>
                                  </li>
                                  <li nz-menu-item>
                                    <a><i nz-icon [type]="'delete'"></i> Delete Comment</a>
                                  </li>
                                  <li nz-menu-item>
                                    <a><i nz-icon [type]="'exclamation-circle'"></i> Mark as a Spam</a>
                                  </li>
                                </ul>
                              </nz-dropdown>
                            </div>
                          </div>
                          <div [innerHtml]="subComment.content"></div>
                          <div>
                            <a href="javascript: void(0);" class="mr-3">
                              <i class="icmn-heart mr-2"></i>
                              <span>{{subComment.likesCount}} Likes</span>
                            </a>
                            <a href="javascript: void(0);" class="mr-3">
                              <i class="icmn-bubble mr-2"></i>
                              <span>{{subComment.commentsCount}}</span>
                            </a>
                            <a href="javascript: void(0);">
                              <i class="icmn-reply mr-2"></i>
                              <span>Reply</span>
                            </a>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div class="mb-5 pb-2">
                <a href="javascript: void(0);" class="btn btn-default btn-block mb-5">
                  Load More
                </a>
              </div>
            </div>
          </div>
        </div>
        <div class="col-lg-4">
          <aside class="sidebar">
            <div class="partition">
              <div class="partitionHead">
                <span class="partitionName">Search</span>
              </div>
              <div class="input-group">
                <nz-input-group [nzSuffix]="suffixIconSearch">
                  <input type="text" nz-input placeholder="input search text">
                </nz-input-group>
                <ng-template #suffixIconSearch>
                  <i nz-icon type="search"></i>
                </ng-template>
              </div>
            </div>
            <div class="partition">
              <div class="partitionHead">
                <span class="partitionName">Categories</span>
              </div>
              <ul class="categoriesList">
                <li class="categoriesItem" *ngFor="let category of articlesCategories">
                  <a class="categoriesLink" href="javascript: void(0);">
                    {{category}}
                  </a>
                </li>
              </ul>
            </div>
            <div class="partition">
              <div class="partitionHead">
                <span class="partitionName">Latest post</span>
              </div>
              <article class="latestPost" *ngFor="let latestArticle of latesArticlesData">
                <div class="latestImg">
                  <a href="javascript: void(0);">
                    <img [src]="latestArticle.cover" alt={{latestArticle.name}}/>
                  </a>
                </div>
                <div class="latestData">
                  <div class="latestName">
                    <h2>
                      <a href="javascript: void(0);">{{latestArticle.name}}</a>
                    </h2>
                  </div>
                  <ul class="latestArticleMeta meta">
                    <li class="metaInf">
                      <span class="articleAuthor">
                        Post By <a href="javascript: void(0);">{{latestArticle.author}}</a>
                      </span>
                    </li>
                    <li class="metaInf">
                      <span class="articleDate">
                        On {{latestArticle.date}}
                      </span>
                    </li>
                  </ul>
                </div>
              </article>
            </div>
            <div class="partition">
              <div class="partitionHead">
                <span class="partitionName">Subscribe</span>
              </div>
              <div class="input-group">
                <nz-input-group [nzAddOnAfter]="addOnAfterIconTemplate">
                  <input type="text" nz-input placeholder="Email">
                </nz-input-group>
                <ng-template #addOnAfterIconTemplate>
                  <i nz-icon type="mail"></i>
                </ng-template>
              </div>
            </div>
          </aside>
        </div>
      </div>
    </div>
  </div>
</section>

// cleanui-admin-template-vue/src/views/blog/post/index.vue
<template>
  <section class="card">
    <div class="card-header">
      <div class="utils__title">
        <strong>Blog Post</strong>
      </div>
    </div>
    <div class="card-body">
      <div :class="$style.blogFeed">
        <div class="row">
          <div class="col-lg-8">
            <main>
              <article :class="$style.article">
                <div :class="$style.information">
                  <div :clas="$style.title">
                    <h1>
                      <a href="javascript: void(0)">{{articleData.name}}</a>
                    </h1>
                  </div>
                  <ul :class="$style.meta">
                    <li :class="$style.metaInf">
                      <span>
                        Post By
                        <a href="javascript: void(0);">{{articleData.author}}</a>
                      </span>
                    </li>
                    <li :class="$style.metaInf">
                      <span :class="$style.articleData">On {{articleData.date}}</span>
                    </li>
                  </ul>
                </div>
                <div :class="$style.content">
                  <div v-html="articleData.content"></div>
                </div>
                <footer :class="$style.footer">
                  <div class="row">
                    <div class="col-8">
                      <div :class="$style.hashtags">
                        <a
                          href="javascript: void(0);"
                          v-for="(tag, index) in articleData.tags"
                          :key="index"
                        >{{tag}}</a>
                      </div>
                    </div>
                    <div class="col-4">
                      <ul :class="$style.share">
                        <li :class="$style.shareItem">
                          <a href="javascript: void(0);">
                            <i class="fa fa-facebook"></i>
                          </a>
                        </li>
                        <li :class="$style.shareItem">
                          <a href="javascript: void(0);">
                            <i class="fa fa-twitter"></i>
                          </a>
                        </li>
                        <li :class="$style.shareItem">
                          <a href="javascript: void(0);">
                            <i class="fa fa-pinterest-p"></i>
                          </a>
                        </li>
                      </ul>
                    </div>
                  </div>
                </footer>
              </article>
            </main>
            <div :class="$style.authorCard" class="clearfix">
              <div :class="$style.authorPhoto">
                <cui-avatar :src="articleData.authorAvatar" :size="110"/>
              </div>
              <div :class="$style.authorInf">
                <span :class="$style.authorName">{{articleData.author}}</span>
                <p :class="$style.authorWords">&ldquo;{{articleData.authorStatus}}&rdquo;</p>
                <div>
                  <a href="javascript: void(0);" class="btn btn-sm btn-primary">View Profile</a>
                </div>
              </div>
            </div>
            <div class="mb-4">
              <div :class="$style.commentsTitle">Leave a comment</div>
              <div :class="$style.addCommentForm">
                <a-form :form="form">
                  <a-form-item>
                    <a-input
                      placeholder="Username"
                      v-decorator="['username', {rules: [{ required: true, message: 'Please input your username!' }]}]"
                    >
                      <a-icon slot="prefix" type="user" style="color: rgba(0,0,0,.25);"/>
                    </a-input>
                  </a-form-item>
                  <a-form-item>
                    <a-input placeholder="Email" v-decorator="['email']">
                      <a-icon slot="prefix" type="mail" style="color: rgba(0,0,0,.25);"/>
                    </a-input>
                  </a-form-item>
                  <a-form-item>
                    <a-textarea :rows="3" placeholder="Your message"></a-textarea>
                  </a-form-item>
                  <a-form-item>
                    <a-button class="mr-2" type="primary" style="width: 200px;">
                      <i class="fa fa-send mr-2"></i> Send
                    </a-button>
                    <a-upload>
                      <a-button>
                        <a-icon type="upload"/>Attach File
                      </a-button>
                    </a-upload>
                  </a-form-item>
                </a-form>
              </div>
            </div>
            <div class="mb-4">
              <div :class="$style.commentsTitle">Comments</div>
              <div class="mt-3">
                <div
                  class="clearfix"
                  :class="[$style.commentItem, postComment.subComments !== undefined ? 'pb-0' : '']"
                  v-for="(postComment, index) in comments"
                  :key="index"
                >
                  <div :class="$style.commentAvatar">
                    <cui-avatar :src="postComment.avatar" :size="50" :bordered="false"/>
                  </div>
                  <div :class="$style.commentContent">
                    <div class="clearfix">
                      <div class="pull-left">
                        <strong>{{postComment.name}}</strong>
                        <br>
                        <small class="tet-muted">{{postComment.date}}</small>
                      </div>
                      <div class="pull-right">
                        <a-dropdown>
                          <a class="ant-dropdown-link" href="javascript: void(0);">Actions
                            <a-icon type="down"/>
                          </a>
                          <a-menu slot="overlay">
                            <a-menu-item>
                              <a href="javascript:void(0)">
                                <a-icon type="edit"/>Edit Post
                              </a>
                            </a-menu-item>
                            <a-menu-item>
                              <a href="javascript:void(0)">
                                <a-icon type="delete"/>Delete Post
                              </a>
                            </a-menu-item>
                            <a-menu-item>
                              <a href="javascript:void(0)">
                                <a-icon type="frown-o"/>Mark as a Spam
                              </a>
                            </a-menu-item>
                          </a-menu>
                        </a-dropdown>
                      </div>
                    </div>
                    <div v-html="postComment.content"></div>
                    <div>
                      <a href="javascript: void(0);" class="mr-3">
                        <i class="icmn-heart mr-2"/>
                        <span v-if="postComment.likesCount > 0">{{postComment.likesCount}} Likes</span>
                        <span v-if="postComment.likesCount === 0">{{postComment.likesCount}} Like</span>
                      </a>
                      <a href="javascript: void(0);" class="mr-3">
                        <i class="icmn-bubble mr-2"/>
                        <span
                          v-if="postComment.commentsCount > 0"
                        >{{postComment.commentsCount}} Comments</span>
                        <span
                          v-if="postComment.commentsCount === 0"
                        >{{postComment.commentsCount}} Comment</span>
                      </a>
                      <a href="javascript: void(0);">
                        <i class="icmn-reply mr-2"/>
                        <span>Reply</span>
                      </a>
                    </div>
                    <div v-if="postComment.subComments">
                      <div :class="$style.subcommentsContent">
                        <div
                          class="clearfix"
                          :class="$style.commentItem"
                          v-for="(subComment, index) in postComment.subComments"
                          :key="index"
                        >
                          <div :class="$style.commentAvatar">
                            <cui-avatar :src="subComment.avatar" :size="50" :bordered="false"/>
                          </div>
                          <div :class="$style.commentContent">
                            <div class="clearfix">
                              <div class="pull-left">
                                <strong>{{postComment.name}}</strong>
                                <br>
                                <small class="tet-muted">{{postComment.date}}</small>
                              </div>
                              <div class="pull-right">
                                <a-dropdown>
                                  <a class="ant-dropdown-link" href="javascript: void(0);">Actions
                                    <a-icon type="down"/>
                                  </a>
                                  <a-menu slot="overlay">
                                    <a-menu-item>
                                      <a href="javascript:void(0)">
                                        <a-icon type="edit"/>Edit Post
                                      </a>
                                    </a-menu-item>
                                    <a-menu-item>
                                      <a href="javascript:void(0)">
                                        <a-icon type="delete"/>Delete Post
                                      </a>
                                    </a-menu-item>
                                    <a-menu-item>
                                      <a href="javascript:void(0)">
                                        <a-icon type="frown-o"/>Mark as a Spam
                                      </a>
                                    </a-menu-item>
                                  </a-menu>
                                </a-dropdown>
                              </div>
                            </div>
                            <div v-html="subComment.content">
                              <div>
                                <a href="javascript: void(0);" class="mr-3">
                                  <i class="icmn-heart mr-2"/>
                                  <span
                                    v-if="postComment.likesCount > 0"
                                  >{{postComment.likesCount}} Likes</span>
                                  <span
                                    v-if="postComment.likesCount === 0"
                                  >{{postComment.likesCount}} Like</span>
                                </a>
                                <a href="javascript: void(0);" class="mr-3">
                                  <i class="icmn-bubble mr-2"/>
                                  <span
                                    v-if="postComment.commentsCount > 0"
                                  >{{postComment.commentsCount}} Comments</span>
                                  <span
                                    v-if="postComment.commentsCount === 0"
                                  >{{postComment.commentsCount}} Comment</span>
                                </a>
                                <a href="javascript: void(0);">
                                  <i class="icmn-reply mr-2"/>
                                  <span>Reply</span>
                                </a>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="mb-5 pb-2">
                  <a href="javascript: void(0);" class="btn btn-default btn-block mb-5">Load More</a>
                </div>
              </div>
            </div>
          </div>
          <div class="col-lg-4">
            <div :class="$style.sidebar">
              <div :class="$style.partition">
                <div :class="$style.partitionHead">
                  <span :class="$style.partitionName">Search</span>
                </div>
                <div class="input-group">
                  <a-input-search placeholder="Search ...">
                    <a-button slot="enterButton" type="primary">
                      <a-icon type="search"/>Search
                    </a-button>
                  </a-input-search>
                </div>
              </div>
              <div :class="$style.partition">
                <div :class="$style.partitionHead">
                  <span :class="$style.partitionName">Categories</span>
                </div>
                <ul :class="$style.categoriesList">
                  <li
                    :class="$style.categoriesItem"
                    v-for="(category, index) in articlesCategories"
                    :key="index"
                  >
                    <a :class="$style.categoriesLink" href="javascript: void(0);">{{category}}</a>
                  </li>
                </ul>
              </div>
              <div :class="$style.partition">
                <div :class="$style.partitionHead">
                  <span :class="$style.partitionName">Latest Post</span>
                </div>
                <article
                  :class="$style.latestPost"
                  v-for="(latestArticle, index) in latesArticlesData"
                  :key="index"
                >
                  <div :class="$style.latestImg">
                    <a href="javascript: void(0);">
                      <img :src="latestArticle.cover" :alt="latestArticle.name">
                    </a>
                  </div>
                  <div :class="$style.latestData">
                    <div :class="$style.latestName">
                      <h2>
                        <a href="javascript: void(0);">{{latestArticle.name}}</a>
                      </h2>
                    </div>
                    <ul :class="[$style.latestArticleMeta, $style.meta]">
                      <li :class="$style.metaInf">
                        <span>
                          Post By
                          <a href="javascript: void(0);">{{latestArticle.author}}</a>
                        </span>
                      </li>
                      <li :class="$style.metaInf">
                        <span :class="$style.articleData">On {{latestArticle.date}}</span>
                      </li>
                    </ul>
                  </div>
                </article>
              </div>
              <div :class="$style.partition">
                <div :class="$style.partitionHead">
                  <span :class="$style.partitionName">Subscribe</span>
                </div>
                <div class="input-group">
                  <a-input placeholder="Email adress">
                    <a-icon type="mail" slot="addonAfter"/>
                  </a-input>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</template>

<script>
import { articleData, articlesCategories, latesArticlesData, comments } from './data.json'
import CuiAvatar from '@/components/CleanUIComponents/Avatar'

export default {
  components: {
    CuiAvatar,
  },
  data: function () {
    return {
      form: this.$form.createForm(this),
      articleData,
      articlesCategories,
      latesArticlesData,
      comments,
    }
  },
}
</script>

<style lang="scss" module>
@import "./style.module.scss";
</style>
