// cleanui-admin-template-angular/src/app/pages/pages/lockscreen/lockscreen.component.ts
import { Component, OnInit } from '@angular/core'

@Component({
  selector: 'app-pages-lockscreen',
  templateUrl: './lockscreen.component.html',
  styleUrls: ['./lockscreen.component.scss'],
})
export class PagesLockscreenComponent implements OnInit {
  backgroundNumber = 1
  fullScreen = false
  ngOnInit(): void {}

  changeBackground(): void {
    if (this.backgroundNumber === 5) {
      this.backgroundNumber = 1
    } else {
      this.backgroundNumber += 1
    }
  }

  changeScreen(): void {
    this.fullScreen = !this.fullScreen
  }
}

<section
  class="login"
  [ngClass]="fullScreen ? 'fullscreen' : 'windowed'"
  [ngStyle]="{'background-image': 'url(\'assets/images/photos/' + backgroundNumber + '.jpeg\')'}"
>
  <header class="header">
    <a href="javascript: void(0);" class="logo">
      <img src="assets/images/logo-inverse.png" alt="Clean UI Admin Template">
    </a>
    <div class="styleControls">
      <button nz-button nzType="default" (click)="changeScreen()">Set {{fullScreen ? 'windowed' : 'fullscreen'}}</button>
      <button nz-button nzType="default" class="ml-3" (click)="changeBackground()">Change Background</button>
    </div>
  </header>
  <div class="content">
    <div class="form">
      <div class="user">
        <cui-avatar src="assets/images/avatars/1.jpg" [bordered]="true" [size]="90"></cui-avatar>
        <p>
          <i class="icmn-lock"></i>
          <strong>Artour Arteezy</strong>
        </p>
      </div>
      <form nz-form class="login-form">
        <nz-form-item>
          <nz-form-control>
            <nz-input-group [nzPrefix]="prefixLock">
              <input formControlName="userPassword" nz-input placeholder="Password">
            </nz-input-group>
          </nz-form-control>
        </nz-form-item>
        <div class="form-actions text-center">
          <button type="submit" class="btn btn-success"w>
            Unlock
          </button>
        </div>
        <div class="text-center">
          <a href="javascript: void(0);" class="text-default">
            Or sign in as a different user
          </a>
        </div>
      </form>
    </div>
  </div>
</section>
<ng-template #prefixLock><i nz-icon type="lock"></i></ng-template>

// cleanui-admin-template-vue/src/views/pages/lockscreen/index.vue
<template>
  <section
    :class="[$style.login, fullscreen ? $style.fullscreen : $style.windowed]"
    :style="{backgroundImage: 'url(\'resources/images/photos/' + backgroundNumber + '.jpeg\')'}"
  >
    <header :class="$style.header">
      <a href="javascript: void(0);" :class="$style.logo">
        <img src="resources/images/logo-inverse.png" alt="Clean UI Admin Template">
      </a>
      <div :class="$style.styleControls">
        <a-button
          class="mt-3 mt-xl-0"
          @click="setFullscreen"
        >Set {{fullscreen ? 'Windowed' : 'Fullscreen'}}</a-button>
        <a-button class="ml-3 mt-3 mt-xl-0" @click="changeBackground">Change Background</a-button>
      </div>
    </header>
    <div :class="$style.content">
      <div :class="$style.form">
        <div :class="$style.user">
          <cui-avatar src="resources/images/avatars/1.jpg" :bordered="true" :size="90"/>
          <p>
            <i class="icmn-lock"/>
            <strong>Artour Arteezy</strong>
          </p>
        </div>
        <a-form class="login-form">
          <a-form-item>
            <a-input type="password" placeholder="Password">
              <a-icon slot="prefix" type="lock" style="color: rgba(0,0,0,.25);"/>
            </a-input>
          </a-form-item>
          <div class="form-actions text-center">
            <button type="submit" class="btn btn-success">Unlock</button>
          </div>
          <div class="text-center">
            <a href="javascript: void(0);" class="text-default">Or sign in as a different user</a>
          </div>
        </a-form>
      </div>
    </div>
  </section>
</template>

<script>
import CuiAvatar from '@/components/CleanUIComponents/Avatar'

export default {
  components: {
    CuiAvatar,
  },
  data: function () {
    return {
      fullscreen: false,
      backgroundNumber: 1,
    }
  },
  methods: {
    changeBackground() {
      if (this.backgroundNumber === 5) {
        this.backgroundNumber = 1
      } else {
        this.backgroundNumber += 1
      }
    },
    setFullscreen() {
      this.fullscreen = !this.fullscreen
    },
  },
}
</script>

<style lang="scss" module>
@import "./style.module.scss";
</style>
