// cleanui-admin-template-react-umi/src/pages/pages/lockscreen/index.js
import React from 'react'
import { Button } from 'antd'
import { Helmet } from 'react-helmet'
import styles from './style.module.scss'
import UnlockForm from './UnlockForm'
import Avatar from '@/components/CleanUIComponents/Avatar'

class Lockscreen extends React.Component {
  state = {
    fullScreen: false,
    backgroundNumber: 1,
  }

  setFullscreen = () => {
    const { fullScreen } = this.state
    this.setState({
      fullScreen: !fullScreen,
    })
  }

  changeBackground = () => {
    let { backgroundNumber } = this.state
    if (backgroundNumber === 5) {
      backgroundNumber = 1
    } else {
      backgroundNumber += 1
    }
    this.setState({
      backgroundNumber,
    })
  }

  render() {
    const { fullScreen, backgroundNumber } = this.state

    return (
      <div>
        <Helmet title="Lockscreen" />
        <section
          className={`${styles.login} ${fullScreen ? styles.fullscreen : styles.windowed}`}
          style={{ backgroundImage: `url('resources/images/photos/${backgroundNumber}.jpeg')` }}
        >
          <header className={styles.header}>
            <a className={styles.logo} href="javascript: void(0);">
              <img src="resources/images/logo-inverse.png" alt="Clean UI Admin Template" />
            </a>
            <div className={styles.styleControls}>
              <Button className="mt-3 mt-xl-0" onClick={this.setFullscreen}>
                {`Set ${fullScreen ? 'Windowed' : 'Fullscreen'}`}
              </Button>
              <Button className="ml-3 mt-3 mt-xl-0" onClick={this.changeBackground}>
                Change Background
              </Button>
            </div>
          </header>
          <div className={styles.content}>
            <div className={styles.form}>
              <div className={styles.user}>
                <Avatar src="resources/images/avatars/1.jpg" border="true" size="90" />
                <p>
                  <i className="icmn-lock" />
                  <strong>Artour Arteezy</strong>
                </p>
              </div>
              <UnlockForm />
            </div>
          </div>
        </section>
      </div>
    )
  }
}

export default Lockscreen

// cleanui-admin-template-vue/src/views/pages/lockscreen/index.vue
<template>
  <section
    :class="[$style.login, fullscreen ? $style.fullscreen : $style.windowed]"
    :style="{backgroundImage: 'url(\'resources/images/photos/' + backgroundNumber + '.jpeg\')'}"
  >
    <header :class="$style.header">
      <a href="javascript: void(0);" :class="$style.logo">
        <img src="resources/images/logo-inverse.png" alt="Clean UI Admin Template">
      </a>
      <div :class="$style.styleControls">
        <a-button
          class="mt-3 mt-xl-0"
          @click="setFullscreen"
        >Set {{fullscreen ? 'Windowed' : 'Fullscreen'}}</a-button>
        <a-button class="ml-3 mt-3 mt-xl-0" @click="changeBackground">Change Background</a-button>
      </div>
    </header>
    <div :class="$style.content">
      <div :class="$style.form">
        <div :class="$style.user">
          <cui-avatar src="resources/images/avatars/1.jpg" :bordered="true" :size="90"/>
          <p>
            <i class="icmn-lock"/>
            <strong>Artour Arteezy</strong>
          </p>
        </div>
        <a-form class="login-form">
          <a-form-item>
            <a-input type="password" placeholder="Password">
              <a-icon slot="prefix" type="lock" style="color: rgba(0,0,0,.25);"/>
            </a-input>
          </a-form-item>
          <div class="form-actions text-center">
            <button type="submit" class="btn btn-success">Unlock</button>
          </div>
          <div class="text-center">
            <a href="javascript: void(0);" class="text-default">Or sign in as a different user</a>
          </div>
        </a-form>
      </div>
    </div>
  </section>
</template>

<script>
import CuiAvatar from '@/components/CleanUIComponents/Avatar'

export default {
  components: {
    CuiAvatar,
  },
  data: function () {
    return {
      fullscreen: false,
      backgroundNumber: 1,
    }
  },
  methods: {
    changeBackground() {
      if (this.backgroundNumber === 5) {
        this.backgroundNumber = 1
      } else {
        this.backgroundNumber += 1
      }
    },
    setFullscreen() {
      this.fullscreen = !this.fullscreen
    },
  },
}
</script>

<style lang="scss" module>
@import "./style.module.scss";
</style>
