// cleanui-admin-template-vue/src/views/ecommerce/product-edit/index.vue
<template>
  <div class="card">
    <div class="card-header">
      <div class="utils__title">
        <strong>Product Edit</strong>
      </div>
    </div>
    <div class="card-body">
      <h4 class="text-black mb-3">
        <strong>Main Parameters</strong>
      </h4>
      <a-form :form="form">
        <div class="row">
          <div class="col-lg-8">
            <div class="row">
              <div class="col-lg-6">
                <a-form-item label="Title">
                  <a-input placeholder="Product title" v-decorator="['title']"/>
                </a-form-item>
              </div>
              <div class="col-lg-6">
                <a-form-item label="SKU">
                  <a-input placeholder="Product SKU" v-decorator="['sku']"/>
                </a-form-item>
              </div>
              <div class="col-lg-12">
                <a-form-item label="Category">
                  <a-tree-select
                    v-decorator="['category']"
                    showSearch
                    placeholder="Please select category"
                    allowClear
                    multiple
                    treeDefaultExpandAll
                  >
                    <a-tree-select-node value="furniture" title="Furniture" key="0">
                      <a-tree-select-node value="tables" title="Tables" key="0-0"/>
                      <a-tree-select-node value="chairs" title="Chairs" key="0-1">
                        <a-tree-select-node
                          value="roundedchairs"
                          title="Rounded Chairs"
                          key="0-1-0"
                        />
                        <a-tree-select-node
                          value="squaredchairs"
                          title="Squared Chairs"
                          key="0-1-1"
                        />
                      </a-tree-select-node>
                    </a-tree-select-node>
                    <a-tree-select-node value="electronics" title="Electronics" key="1">
                      <a-tree-select-node value="tv" title="TV" key="1-0"/>
                      <a-tree-select-node value="consoles" title="Consoles" key="1-1">
                        <a-tree-select-node value="playstation" title="Playstation" key="1-1-0"/>
                        <a-tree-select-node value="xbox" title="Xbox" key="1-1-1"/>
                      </a-tree-select-node>
                    </a-tree-select-node>
                  </a-tree-select>
                </a-form-item>
                <a-form-item label="Short Description">
                  <a-textarea
                    placeholder="Short Description"
                    :rows="4"
                    v-decorator="['shortDescr']"
                  />
                </a-form-item>
                <a-form-item label="Full Description">
                  <a-textarea placeholder="Full Description" :rows="4" v-decorator="['fullDescr']"/>
                </a-form-item>
              </div>
            </div>
            <h4 class="text-black mt-2 mb-3">
              <strong>Pricing</strong>
            </h4>
            <div class="row">
              <div class="col-lg-6">
                <a-form-item label="Total Price">
                  <a-input placeholder="Total Price" v-decorator="['total']"/>
                </a-form-item>
              </div>
              <div class="col-lg-6">
                <a-form-item label="Discount Price">
                  <a-input placeholder="Discount Price" v-decorator="['discount']"/>
                </a-form-item>
              </div>
            </div>
            <h4 class="text-black mt-2 mb-3">
              <strong>Attributes</strong>
            </h4>
            <div class="row">
              <div class="col-lg-6">
                <a-form-item label="Colors">
                  <a-select showSearch placeholder="Select a color">
                    <a-select-option value="red">Red</a-select-option>
                    <a-select-option value="black">Black</a-select-option>
                    <a-select-option value="cyan">Cyan</a-select-option>
                    <a-select-option value="blue">Blue</a-select-option>
                  </a-select>
                </a-form-item>
              </div>
              <div class="col-lg-6">
                <a-form-item label="Size">
                  <a-select showSearch placeholder="Select a size">
                    <a-select-option value="red">Red</a-select-option>
                    <a-select-option value="black">Black</a-select-option>
                    <a-select-option value="cyan">Cyan</a-select-option>
                    <a-select-option value="blue">Blue</a-select-option>
                  </a-select>
                </a-form-item>
              </div>
              <div class="col-lg-12">
                <div class="form-actions">
                  <a-button type="primary" class="mr-2">Save Product</a-button>
                  <a-button type="default">Cancel</a-button>
                </div>
              </div>
            </div>
          </div>
          <div class="col-lg-4">
            <div class="mb-4 height-300">
              <a-upload-dragger
                name="file"
                :multiple="true"
                action="//jsonplaceholder.typicode.com/posts/"
                @change="handleChange"
              >
                <p class="ant-upload-drag-icon">
                  <a-icon type="inbox"/>
                </p>
                <p class="ant-upload-text">Click or drag file to this area to upload</p>
                <p
                  class="ant-upload-hint"
                >Support for a single or bulk upload. Strictly prohibit from uploading company data or other band files</p>
              </a-upload-dragger>
            </div>
            <a-upload name="file" :multiple="true">
              <a-button>
                <a-icon type="upload"/>Click to Upload
              </a-button>
            </a-upload>
          </div>
        </div>
      </a-form>
    </div>
  </div>
</template>

<script>
export default {
  data: function () {
    return {
      form: this.$form.createForm(this),
    }
  },
  methods: {
    handleChange(info) {
      const status = info.file.status
      if (status !== 'uploading') {
        console.log(info.file, info.fileList)
      }
      if (status === 'done') {
        this.$message.success(`${info.file.name} file uploaded successfully.`)
      } else if (status === 'error') {
        this.$message.error(`${info.file.name} file upload failed.`)
      }
    },
  },
}
</script>

// cleanui-admin-template-angular/src/app/pages/ecommerce/product-edit/product-edit.component.ts
import { Component } from '@angular/core'

@Component({
  selector: 'app-ecommerce-product-edit',
  templateUrl: './product-edit.component.html',
})
export class EcommerceProductEditComponent {
  nodes = [
    {
      title: 'Furniture',
      key: '0',
      children: [
        {
          title: 'Tables',
          key: '0-0',
        },
        {
          title: 'Chairs',
          key: '0-1',
          children: [
            {
              title: 'Rounded Chairs',
              key: '0-1-0',
            },
            {
              title: 'Squared Chairs',
              key: '0-1-1',
            },
          ],
        },
      ],
    },
    {
      title: 'Electronics',
      key: '1',
      children: [
        {
          title: 'TV',
          key: '1-0',
        },
        {
          title: 'Consoles',
          key: '1-1',
          children: [
            {
              title: 'Playstation',
              key: '1-1-0',
            },
            {
              title: 'X-Box',
              key: '1-1-1',
            },
          ],
        },
      ],
    },
  ]
}

<div class="card">
  <div class="card-header">
    <div class="utils__title">
      <strong>Product Edit</strong>
    </div>
  </div>
  <div class="card-body">
    <h4 class="text-black mb-3">
      <strong>Main Parameters</strong>
    </h4>
    <form nz-form nzLayout="'vertical'">
      <div class="row">
        <div class="col-lg-8">
          <div class="row">
            <div class="col-lg-6">
              <nz-form-item>
                <nz-form-label nzFor="title">Title</nz-form-label>
                <nz-form-control>
                  <input nz-input name="title" type="text" id="title" placeholder="Product title">
                </nz-form-control>
              </nz-form-item >
            </div>
            <div class="col-lg-6">
              <nz-form-item>
                <nz-form-label nzFor="sku">SKU</nz-form-label>
                <nz-form-control>
                  <input nz-input name="sku" type="text" id="sku" placeholder="Product SKU">
                </nz-form-control>
              </nz-form-item >
            </div>
            <div class="col-lg-12">
              <nz-form-item>
                <nz-form-label nzFor="category">Product category</nz-form-label>
                <nz-form-control>
                  <nz-tree-select
                    id="category"
                    style="width: 100%; display: block;"
                    [nzNodes]="nodes"
                    nzShowSearch
                    nzPlaceHolder="Product Category">
                  </nz-tree-select>
                </nz-form-control>
              </nz-form-item>
              <nz-form-item>
                <nz-form-label nzFor="shortDescr">Short Description</nz-form-label>
                <nz-form-control>
                  <textarea rows="3" nz-input id="shortDescr"></textarea>
                </nz-form-control>
              </nz-form-item>
              <nz-form-item>
                <nz-form-label nzFor="fullDescr">Full Description</nz-form-label>
                <nz-form-control>
                  <textarea rows="3" nz-input id="fullDescr"></textarea>
                </nz-form-control>
              </nz-form-item>
            </div>
          </div>
          <h4 class="text-black mt-2 mb-3">
            <strong>Pricing</strong>
          </h4>
          <div class="row">
            <div class="col-lg-6">
              <nz-form-item>
                <nz-form-label nzFor="totalPrice">Total Price</nz-form-label>
                <nz-form-control>
                  <input nz-input name="totalPrice" type="text" id="totalPrice" placeholder="Total Price">
                </nz-form-control>
              </nz-form-item>
            </div>
            <div class="col-lg-6">
              <nz-form-item>
                <nz-form-label nzFor="discPrice">Discount Price</nz-form-label>
                <nz-form-control>
                  <input nz-input name="discPrice" type="text" id="discPrice" placeholder="Discount Price">
                </nz-form-control>
              </nz-form-item>
            </div>
          </div>
          <h4 class="text-black mt-2 mb-3">
            <strong>Attributes</strong>
          </h4>
          <div class="row">
            <div class="col-lg-6">
              <nz-form-item>
                <nz-form-label nzFor="totalPrice">Colors</nz-form-label>
                <nz-form-control>
                  <nz-select style="width: 100%; display: block;" nzPlaceHolder="Choose product color">
                    <nz-option nzValue="blue" nzLabel="Blue"></nz-option>
                    <nz-option nzValue="red" nzLabel="Red"></nz-option>
                    <nz-option nzValue="green" nzLabel="Green"></nz-option>
                  </nz-select>
                </nz-form-control>
              </nz-form-item>
            </div>
            <div class="col-lg-6">
              <nz-form-item>
                <nz-form-label nzFor="totalPrice">Size</nz-form-label>
                <nz-form-control>
                  <nz-select style="width: 100%; display: block;" nzPlaceHolder="Choose product size">
                    <nz-option nzValue="s" nzLabel="Small"></nz-option>
                    <nz-option nzValue="m" nzLabel="Middle"></nz-option>
                    <nz-option nzValue="xl" nzLabel="Extra large"></nz-option>
                  </nz-select>
                </nz-form-control>
              </nz-form-item>
            </div>
            <div class="col-lg-12">
              <div class="form-actions">
                <button nz-button nzType="primary" class="mr-2">Save Product</button>
                <button nz-button>Cancel</button>
              </div>
            </div>
          </div>
        </div>
        <div class="col-lg-4">
          <nz-upload
            class="height-300 mb-3 d-block"
            nzType="drag"
            [nzMultiple]="true"
            [nzLimit]="2"
            nzAction="https://jsonplaceholder.typicode.com/posts/"
          >
            <p class="ant-upload-drag-icon">
              <i nz-icon type="inbox"></i>
            </p>
            <p class="ant-upload-text">Click or drag file to this area to upload</p>
            <p class="ant-upload-hint">Support for a single or bulk upload. Strictly prohibit from uploading company data or other band files</p>
          </nz-upload>
          <nz-upload
            nzAction="https://jsonplaceholder.typicode.com/posts/">
            <button nz-button>
              <i nz-icon type="upload"></i><span>Click to Upload</span>
            </button>
          </nz-upload>
        </div>
      </div>
    </form>
  </div>
</div>
